import type { DashboardCopy } from "../../domain/dashboard/types";
import type { DashboardLanguage } from "../languages";
import { defineLocaleResources } from "../resourceBuilder";

const en: DashboardCopy = {
  panelTitle: "Codex Accounts Manager quota summary",
  brandSub: "Main dashboard for multi-account switching and quota tracking",
  refreshPage: "Refresh Page",
  addAccount: "Add Account",
  importCurrent: "Import Current",
  refreshAll: "Refresh Quotas",
  dashboardTitle: "Codex Accounts Manager · Quota Dashboard",
  dashboardSub: "Primary dashboard for monitoring, management, and screenshots",
  empty: "No saved accounts yet",
  noActiveAccountTitle: "No active account",
  noActiveAccountSub: "Saved accounts exist, but none is currently marked as active.",
  current: "Current",
  hourlyLabel: "5h",
  weeklyLabel: "Weekly",
  reviewLabel: "Review",
  userId: "User ID",
  lastRefresh: "Last Refresh",
  accountId: "Account ID",
  organization: "Organization",
  savedAccounts: "Saved Accounts",
  savedAccountsSub: "Manage saved accounts here, including switching, refresh, details, and removal.",
  teamName: "Team Name",
  login: "Login",
  switchBtn: "Switch",
  refreshBtn: "Refresh",
  detailsBtn: "Details",
  removeBtn: "Remove",
  settingsTitle: "Settings",
  showSensitive: "Show sensitive info",
  hideSensitive: "Hide sensitive info",
  codexAppRestartTitle: "Codex App Restart Policy",
  codexAppRestartSub: "Control how the extension handles a currently running Codex App when switching accounts.",
  restartModeAuto: "Restart automatically",
  restartModeAutoDesc: "If Codex App is already running, restart it immediately after switching accounts.",
  restartModeManual: "Ask every time",
  restartModeManualDesc: "Keep the final decision in your hands and confirm each restart manually.",
  restartModeNote:
    "The extension only restarts Codex App when it is already running. It will not launch the desktop app from a stopped state.",
  autoRefreshTitle: "Automatic Quota Refresh",
  autoRefreshSub: "Refresh saved account quotas on a timer.",
  autoRefreshOn: "Enable auto refresh",
  autoRefreshOnDesc: "Refresh all saved account quotas on a fixed schedule.",
  autoRefreshOff: "Off",
  autoRefreshOffDesc: "Disable timed refresh and refresh manually when needed.",
  autoRefreshValueTemplate: "{value} min",
  autoRefreshValueDescTemplate: "Refresh quotas for all saved accounts every {value} minutes.",
  autoSwitchTitle: "Automatic Account Switching",
  autoSwitchSub: "When the active account quota gets low, switch to another saved account automatically.",
  autoSwitchOn: "Enable auto switch",
  autoSwitchOnDesc:
    "Attempt to switch to another saved account after refresh when the active quota crosses your limit.",
  autoSwitchOff: "Off",
  autoSwitchOffDesc: "Keep the current account until you switch manually.",
  autoSwitchThresholdSuffix: "switch threshold",
  autoSwitchThresholdDescTemplate: "Try switching when {label} remaining quota is {value}% or lower.",
  autoSwitchAnyNote: "Any threshold hit will trigger a switch attempt.",
  autoSwitchToastSwitched: "Active quota reached the auto-switch threshold. Switched to {account}.",
  appPathTitle: "Codex App Launch Path",
  appPathSub: "Optional. Set a custom desktop app path or leave it empty for auto-detection.",
  appPathEmpty: "No app path detected. Please choose one manually.",
  pickPath: "Choose Path",
  clearPath: "Auto-Detect Path",
  dashboardSettingsTitle: "Dashboard Display",
  dashboardSettingsSub: "Control what the quota dashboard shows.",
  showReviewOn: "Show Code Review quota",
  showReviewOnDesc: "Display Code Review quota in the dashboard and account cards.",
  showReviewOff: "Hide Code Review quota",
  showReviewOffDesc: "Keep the dashboard simpler with only 5-hour and weekly quotas.",
  warningTitle: "Quota Warning",
  warningSub: "Show a warning when the active account's 5-hour or weekly remaining quota drops below the threshold.",
  warningOn: "Enable warning",
  warningOnDesc: "Show notifications after refresh when either 5-hour or weekly remaining quota is below the threshold.",
  warningOff: "Disable warning",
  warningOffDesc: "Do not show quota threshold notifications.",
  warningValueDescTemplate: "Warn when available quota drops below {value}%.",
  colorThresholdTitle: "Quota Color Thresholds",
  colorThresholdSub: "Control when quotas appear green, yellow, or red.",
  colorThresholdGreenTitle: "Green starts at",
  colorThresholdYellowTitle: "Yellow starts at",
  colorThresholdGreenDescTemplate: "Show green when available quota is at least {value}%.",
  colorThresholdYellowDescTemplate:
    "Show yellow when available quota is at least {value}% and below the green threshold.",
  colorThresholdRedNoteTemplate: "Show red when available quota falls below {value}%.",
  debugTitle: "Network Debug Logs",
  debugSub: "Control whether request summaries are written to the output panel.",
  debugOn: "Enable debug logs",
  debugOnDesc: "Record sanitized request results to help troubleshoot API issues.",
  debugOff: "Disable debug logs",
  debugOffDesc: "Default off to avoid noisy debugging output.",
  debugNote: "Logs are written to the `Codex Accounts Network` output channel with truncation and redaction applied.",
  languageTitle: "Language",
  languageSub: "Override the dashboard and prompt language for this extension only.",
  languageAuto: "Auto (follow VS Code)",
  languageZh: "Simplified Chinese",
  languageEn: "English",
  languageNote: "Changes apply immediately to this extension only and do not affect the rest of the VS Code UI.",
  statusShort: "Status",
  statusToggleTip: "Control whether this account appears in the bottom status popup",
  statusToggleTipChecked: "This account is already shown in the bottom status popup. Click to remove it",
  statusLimitTip: "You can show at most 2 extra accounts in the status popup. Uncheck one first",
  unknown: "unknown",
  never: "never",
  resetUnknown: "reset unknown"
};

export const dashboardCopyResources = defineLocaleResources(en, {
  zh: {
    panelTitle: "Codex Accounts Manager 配额总览",
    brandSub: "多账号切换与配额监控主面板",
    refreshPage: "刷新页面",
    addAccount: "添加账号",
    importCurrent: "导入当前账号",
    refreshAll: "刷新配额",
    dashboardTitle: "Codex Accounts Manager · 配额总览",
    dashboardSub: "主面板视图，适合停留查看和截图",
    empty: "还没有保存账号",
    noActiveAccountTitle: "当前没有激活账号",
    noActiveAccountSub: "已保存账号存在，但当前没有任何账号被标记为激活。",
    current: "当前",
    hourlyLabel: "5小时",
    weeklyLabel: "每周",
    reviewLabel: "代码审查",
    userId: "用户 ID",
    lastRefresh: "最近刷新",
    accountId: "账号 ID",
    organization: "组织",
    savedAccounts: "已保存账号",
    savedAccountsSub: "集中管理已保存账号，支持切换、刷新、查看详情和删除。",
    teamName: "团队空间",
    login: "登录方式",
    switchBtn: "切换",
    refreshBtn: "刷新",
    detailsBtn: "详情",
    removeBtn: "删除",
    settingsTitle: "设置",
    showSensitive: "显示隐私信息",
    hideSensitive: "隐藏隐私信息",
    codexAppRestartTitle: "Codex App 重启策略",
    codexAppRestartSub: "控制切换账号时，如何处理本机已在运行中的 Codex App。",
    restartModeAuto: "帮我自动重启",
    restartModeAutoDesc: "如果 Codex App 当前正在运行，切换账号后直接重启它。",
    restartModeManual: "每次手动点击重启",
    restartModeManualDesc: "保留最终确认权。切换账号后由你决定是否立即重启。",
    restartModeNote: "只有当 Codex App 当前已经在运行时，才会执行重启。若应用未启动，扩展不会强行拉起。",
    autoRefreshTitle: "配额自动刷新",
    autoRefreshSub: "定时刷新当前已保存账号的配额数据。",
    autoRefreshOn: "开启自动刷新",
    autoRefreshOnDesc: "按固定时间间隔自动刷新全部账号配额。",
    autoRefreshOff: "关闭",
    autoRefreshOffDesc: "不自动刷新，由你手动控制。",
    autoRefreshValueTemplate: "{value} 分钟",
    autoRefreshValueDescTemplate: "每 {value} 分钟自动刷新一次全部账号配额。",
    autoSwitchTitle: "自动切号",
    autoSwitchSub: "当前激活账号配额过低时，自动切换到其他已保存账号。",
    autoSwitchOn: "开启自动切号",
    autoSwitchOnDesc: "刷新后如果当前账号触达阈值，会尝试自动切换到其他可用账号。",
    autoSwitchOff: "关闭",
    autoSwitchOffDesc: "保持当前账号不变，由你手动切换。",
    autoSwitchThresholdSuffix: "切号阈值",
    autoSwitchThresholdDescTemplate: "当 {label} 剩余配额低于或等于 {value}% 时，尝试自动切换。",
    autoSwitchAnyNote: "任一阈值命中后都会触发一次切号尝试。",
    autoSwitchToastSwitched: "当前账号已触发自动切号阈值，已切换到 {account}。",
    appPathTitle: "Codex App 启动路径",
    appPathSub: "可选。你可以指定本机 Codex App 的自定义路径；留空则使用自动检测。",
    appPathEmpty: "未检测到启动路径，请手动选择。",
    pickPath: "选择路径",
    clearPath: "自动检测路径",
    dashboardSettingsTitle: "仪表盘显示",
    dashboardSettingsSub: "控制总览面板中显示哪些信息。",
    showReviewOn: "显示 Code Review 配额",
    showReviewOnDesc: "在总览和账号卡片中展示 Code Review 配额。",
    showReviewOff: "隐藏 Code Review 配额",
    showReviewOffDesc: "精简仪表盘，只显示 5 小时和每周配额。",
    warningTitle: "超额预警",
    warningSub: "当前账号的 5 小时或每周剩余配额低于阈值时弹出提醒。",
    warningOn: "开启预警",
    warningOnDesc: "刷新后如果 5 小时或每周剩余配额任一低于阈值，会弹出通知提醒。",
    warningOff: "关闭预警",
    warningOffDesc: "不做额度阈值提醒。",
    warningValueDescTemplate: "当可用配额低于 {value}% 时提醒。",
    colorThresholdTitle: "配额颜色阈值",
    colorThresholdSub: "控制绿色、黄色和红色的显示区间。",
    colorThresholdGreenTitle: "绿色起点",
    colorThresholdYellowTitle: "黄色起点",
    colorThresholdGreenDescTemplate: "剩余配额大于等于 {value}% 时显示绿色。",
    colorThresholdYellowDescTemplate: "剩余配额大于等于 {value}% 且低于绿色阈值时显示黄色。",
    colorThresholdRedNoteTemplate: "低于 {value}% 的配额会显示为红色。",
    debugTitle: "网络调试日志",
    debugSub: "控制是否将接口请求摘要写入输出面板。",
    debugOn: "开启调试日志",
    debugOnDesc: "记录脱敏后的请求结果，便于排查接口异常。",
    debugOff: "关闭调试日志",
    debugOffDesc: "默认关闭，避免无关调试输出。",
    debugNote: "日志会写入 `Codex Accounts Network` 输出通道，并对敏感字段做截断和脱敏处理。",
    languageTitle: "语言",
    languageSub: "覆盖总览面板和提示文案的语言，仅对本扩展生效。",
    languageAuto: "自动（跟随 VS Code）",
    languageZh: "简体中文",
    languageEn: "English",
    languageNote: "修改后会立即应用到本扩展的面板和提示文案，不影响 VS Code 其他界面语言。",
    statusShort: "状态栏",
    statusToggleTip: "控制该账号是否显示在底部状态栏弹窗中",
    statusToggleTipChecked: "已显示在底部状态栏弹窗中，点击可取消",
    statusLimitTip: "状态栏最多显示 2 个额外账号，请先取消一个已勾选账号",
    unknown: "未知",
    never: "从未",
    resetUnknown: "重置时间未知"
  },
  "zh-hant": {
    panelTitle: "Codex Accounts Manager 配額總覽",
    brandSub: "多帳號切換與配額監控主面板",
    refreshPage: "重新整理頁面",
    addAccount: "新增帳號",
    importCurrent: "匯入目前帳號",
    refreshAll: "重新整理配額",
    dashboardTitle: "Codex Accounts Manager · 配額總覽",
    dashboardSub: "主面板視圖，適合停留查看與截圖",
    empty: "尚未儲存任何帳號",
    noActiveAccountTitle: "目前沒有啟用帳號",
    noActiveAccountSub: "已有已儲存帳號，但目前沒有任何帳號被標記為啟用。",
    current: "目前",
    hourlyLabel: "5小時",
    weeklyLabel: "每週",
    reviewLabel: "程式碼審查",
    userId: "使用者 ID",
    lastRefresh: "最近重新整理",
    accountId: "帳號 ID",
    organization: "組織",
    savedAccounts: "已儲存帳號",
    savedAccountsSub: "集中管理已儲存帳號，支援切換、重新整理、查看詳情與刪除。",
    teamName: "團隊空間",
    login: "登入方式",
    switchBtn: "切換",
    refreshBtn: "重新整理",
    detailsBtn: "詳情",
    removeBtn: "刪除",
    settingsTitle: "設定",
    codexAppRestartTitle: "Codex App 重新啟動策略",
    codexAppRestartSub: "控制切換帳號時，如何處理本機已在執行中的 Codex App。",
    restartModeAuto: "幫我自動重新啟動",
    restartModeAutoDesc: "如果 Codex App 目前正在執行，切換帳號後直接重新啟動它。",
    restartModeManual: "每次手動點擊重新啟動",
    restartModeManualDesc: "保留最終確認權。切換帳號後由你決定是否立即重新啟動。",
    restartModeNote: "只有當 Codex App 目前已在執行時，才會執行重新啟動。若應用程式未啟動，擴充功能不會強制拉起。",
    autoRefreshTitle: "配額自動重新整理",
    autoRefreshSub: "定時重新整理目前已儲存帳號的配額資料。",
    autoRefreshOn: "開啟自動重新整理",
    autoRefreshOnDesc: "按固定時間間隔自動重新整理全部帳號配額。",
    autoRefreshOff: "關閉",
    autoRefreshOffDesc: "不自動重新整理，由你手動控制。",
    autoRefreshValueTemplate: "{value} 分鐘",
    autoRefreshValueDescTemplate: "每 {value} 分鐘自動重新整理一次全部帳號配額。",
    autoSwitchTitle: "自動切換帳號",
    autoSwitchSub: "目前啟用帳號配額過低時，自動切換到其他已儲存帳號。",
    autoSwitchOn: "開啟自動切換帳號",
    autoSwitchOnDesc: "重新整理後若目前帳號觸及門檻，會嘗試自動切換到其他可用帳號。",
    autoSwitchOff: "關閉",
    autoSwitchOffDesc: "保持目前帳號不變，由你手動切換。",
    autoSwitchThresholdSuffix: "切換門檻",
    autoSwitchThresholdDescTemplate: "當 {label} 剩餘配額低於或等於 {value}% 時，嘗試自動切換。",
    autoSwitchAnyNote: "任一門檻命中後都會觸發一次切換嘗試。",
    autoSwitchToastSwitched: "目前帳號已觸發自動切換門檻，已切換到 {account}。",
    appPathTitle: "Codex App 啟動路徑",
    appPathSub: "選填。你可以指定本機 Codex App 的自訂路徑；留空則使用自動偵測。",
    appPathEmpty: "未偵測到啟動路徑，請手動選擇。",
    pickPath: "選擇路徑",
    clearPath: "自動偵測路徑",
    dashboardSettingsTitle: "儀表板顯示",
    dashboardSettingsSub: "控制總覽面板中顯示哪些資訊。",
    showReviewOn: "顯示 Code Review 配額",
    showReviewOnDesc: "在總覽和帳號卡片中顯示 Code Review 配額。",
    showReviewOff: "隱藏 Code Review 配額",
    showReviewOffDesc: "精簡儀表板，只顯示 5 小時和每週配額。",
    warningTitle: "配額警示",
    warningSub: "當目前帳號的 5 小時或每週剩餘配額低於門檻時彈出提醒。",
    warningOn: "開啟警示",
    warningOnDesc: "重新整理後若 5 小時或每週剩餘配額任一低於門檻，會彈出通知提醒。",
    warningOff: "關閉警示",
    warningOffDesc: "不進行額度門檻提醒。",
    warningValueDescTemplate: "當可用配額低於 {value}% 時提醒。",
    colorThresholdTitle: "配額顏色門檻",
    colorThresholdSub: "控制綠色、黃色和紅色的顯示區間。",
    colorThresholdGreenTitle: "綠色起點",
    colorThresholdYellowTitle: "黃色起點",
    colorThresholdGreenDescTemplate: "剩餘配額大於等於 {value}% 時顯示綠色。",
    colorThresholdYellowDescTemplate: "剩餘配額大於等於 {value}% 且低於綠色門檻時顯示黃色。",
    colorThresholdRedNoteTemplate: "低於 {value}% 的配額會顯示為紅色。",
    debugTitle: "網路除錯日誌",
    debugSub: "控制是否將介面請求摘要寫入輸出面板。",
    debugOn: "開啟除錯日誌",
    debugOnDesc: "記錄去敏後的請求結果，便於排查 API 異常。",
    debugOff: "關閉除錯日誌",
    debugOffDesc: "預設關閉，避免無關的除錯輸出。",
    debugNote: "日誌會寫入 `Codex Accounts Network` 輸出通道，並對敏感欄位進行截斷與去敏處理。",
    languageTitle: "語言",
    languageSub: "覆寫本擴充功能的儀表板與提示文案語言。",
    languageAuto: "自動（跟隨 VS Code）",
    languageZh: "簡體中文",
    languageEn: "English",
    languageNote: "變更會立即套用到本擴充功能，不會影響 VS Code 其他介面語言。",
    statusShort: "狀態列",
    statusToggleTip: "控制此帳號是否顯示在底部狀態列彈窗中",
    statusToggleTipChecked: "已顯示在底部狀態列彈窗中，點擊可取消",
    statusLimitTip: "狀態列最多顯示 2 個額外帳號，請先取消一個已勾選帳號",
    unknown: "未知",
    never: "從未",
    resetUnknown: "重置時間未知"
  },
  ja: {
    panelTitle: "Codex Accounts Manager クォータ概要",
    brandSub: "複数アカウントの切り替えとクォータ監視のメインダッシュボード",
    refreshPage: "ページを更新",
    addAccount: "アカウントを追加",
    importCurrent: "現在のアカウントを取り込む",
    refreshAll: "クォータを更新",
    dashboardTitle: "Codex Accounts Manager · クォータダッシュボード",
    dashboardSub: "監視、管理、スクリーンショットに適したメインダッシュボード",
    empty: "保存済みアカウントはまだありません",
    noActiveAccountTitle: "アクティブなアカウントがありません",
    noActiveAccountSub: "保存済みアカウントはありますが、現在アクティブとしてマークされたアカウントがありません。",
    current: "現在",
    hourlyLabel: "5時間",
    weeklyLabel: "週次",
    reviewLabel: "レビュー",
    userId: "ユーザー ID",
    lastRefresh: "最終更新",
    accountId: "アカウント ID",
    organization: "組織",
    savedAccounts: "保存済みアカウント",
    savedAccountsSub: "保存済みアカウントをここで管理し、切り替え、更新、詳細確認、削除を行えます。",
    teamName: "チーム",
    login: "ログイン",
    switchBtn: "切り替え",
    refreshBtn: "更新",
    detailsBtn: "詳細",
    removeBtn: "削除",
    settingsTitle: "設定",
    codexAppRestartTitle: "Codex App の再起動ポリシー",
    codexAppRestartSub: "アカウント切り替え時に、現在起動中の Codex App をどう扱うかを設定します。",
    restartModeAuto: "自動で再起動する",
    restartModeAutoDesc: "Codex App が起動中なら、アカウント切り替え後すぐに再起動します。",
    restartModeManual: "毎回手動で確認する",
    restartModeManualDesc: "最終判断を自分で行い、再起動のたびに確認します。",
    restartModeNote: "Codex App がすでに起動している場合のみ再起動します。停止中の状態からは起動しません。",
    autoRefreshTitle: "自動クォータ更新",
    autoRefreshSub: "保存済みアカウントのクォータを定期的に更新します。",
    autoRefreshOn: "自動更新を有効にする",
    autoRefreshOnDesc: "保存済みアカウントのクォータを一定間隔で更新します。",
    autoRefreshOff: "オフ",
    autoRefreshOffDesc: "定期更新を無効にし、必要なときだけ手動で更新します。",
    autoRefreshValueTemplate: "{value} 分",
    autoRefreshValueDescTemplate: "保存済みアカウントのクォータを {value} 分ごとに更新します。",
    autoSwitchTitle: "自動アカウント切り替え",
    autoSwitchSub: "現在のアクティブアカウントのクォータが低くなったら、別の保存済みアカウントへ自動で切り替えます。",
    autoSwitchOn: "自動切り替えを有効にする",
    autoSwitchOnDesc: "更新後に現在のアカウントがしきい値に達した場合、別の利用可能なアカウントへの切り替えを試みます。",
    autoSwitchOff: "オフ",
    autoSwitchOffDesc: "現在のアカウントを維持し、必要なときに手動で切り替えます。",
    autoSwitchThresholdSuffix: "切り替えしきい値",
    autoSwitchThresholdDescTemplate: "{label} の残りクォータが {value}% 以下になったら切り替えを試みます。",
    autoSwitchAnyNote: "どちらか一方のしきい値に達すると切り替えを試みます。",
    autoSwitchToastSwitched: "アクティブなクォータが自動切り替えのしきい値に達したため、{account} に切り替えました。",
    appPathTitle: "Codex App 起動パス",
    appPathSub: "任意設定です。Codex App のカスタムパスを指定するか、空欄のまま自動検出を使用します。",
    appPathEmpty: "起動パスが見つかりません。手動で選択してください。",
    pickPath: "パスを選択",
    clearPath: "自動検出パス",
    dashboardSettingsTitle: "ダッシュボード表示",
    dashboardSettingsSub: "クォータダッシュボードに表示する情報を設定します。",
    showReviewOn: "Code Review クォータを表示",
    showReviewOnDesc: "ダッシュボードとアカウントカードに Code Review クォータを表示します。",
    showReviewOff: "Code Review クォータを非表示",
    showReviewOffDesc: "5時間と週次クォータのみを表示してダッシュボードを簡潔にします。",
    warningTitle: "クォータ警告",
    warningSub: "現在のアカウントの5時間または週次の残りクォータがしきい値を下回ると警告を表示します。",
    warningOn: "警告を有効にする",
    warningOnDesc: "更新後に5時間または週次の残りクォータのいずれかがしきい値を下回ると通知を表示します。",
    warningOff: "警告を無効にする",
    warningOffDesc: "クォータしきい値の通知を表示しません。",
    warningValueDescTemplate: "利用可能なクォータが {value}% を下回ったら警告します。",
    colorThresholdTitle: "クォータ色のしきい値",
    colorThresholdSub: "クォータが緑、黄、赤で表示される条件を設定します。",
    colorThresholdGreenTitle: "緑の開始値",
    colorThresholdYellowTitle: "黄の開始値",
    colorThresholdGreenDescTemplate: "利用可能クォータが {value}% 以上で緑色を表示します。",
    colorThresholdYellowDescTemplate: "利用可能クォータが {value}% 以上かつ緑のしきい値未満で黄色を表示します。",
    colorThresholdRedNoteTemplate: "利用可能クォータが {value}% 未満になると赤色で表示します。",
    debugTitle: "ネットワークデバッグログ",
    debugSub: "リクエスト概要を出力パネルに書き出すかどうかを制御します。",
    debugOn: "デバッグログを有効にする",
    debugOnDesc: "サニタイズ済みのリクエスト結果を記録して API 問題の調査に役立てます。",
    debugOff: "デバッグログを無効にする",
    debugOffDesc: "不要なデバッグ出力を避けるため既定では無効です。",
    debugNote: "`Codex Accounts Network` 出力チャネルにログを書き込み、機密情報は切り詰め・マスクされます。",
    languageTitle: "言語",
    languageSub: "この拡張機能のみのダッシュボードと言語表示を上書きします。",
    languageAuto: "自動（VS Code に追従）",
    languageZh: "簡体字中国語",
    languageEn: "English",
    languageNote: "変更はこの拡張機能にのみ即時反映され、VS Code 全体の表示言語には影響しません。",
    statusShort: "ステータス",
    statusToggleTip: "このアカウントを下部のステータスポップアップに表示するかどうかを切り替えます",
    statusToggleTipChecked:
      "このアカウントはすでに下部のステータスポップアップに表示されています。クリックすると外せます",
    statusLimitTip: "ステータスポップアップには追加で 2 アカウントまで表示できます。先に 1 つ外してください",
    unknown: "不明",
    never: "なし",
    resetUnknown: "リセット時刻不明"
  },
  es: {
    panelTitle: "Resumen de cuota de Codex Accounts Manager",
    brandSub: "Panel principal para cambiar entre cuentas y monitorear cuotas",
    refreshPage: "Actualizar página",
    addAccount: "Agregar cuenta",
    importCurrent: "Importar cuenta actual",
    refreshAll: "Actualizar cuotas",
    dashboardTitle: "Codex Accounts Manager · Panel de cuotas",
    dashboardSub: "Panel principal para monitoreo, gestión y capturas",
    empty: "Todavía no hay cuentas guardadas",
    noActiveAccountTitle: "No hay una cuenta activa",
    noActiveAccountSub: "Hay cuentas guardadas, pero ninguna está marcada actualmente como activa.",
    current: "Actual",
    hourlyLabel: "5 h",
    weeklyLabel: "Semanal",
    reviewLabel: "Revisión",
    userId: "ID de usuario",
    lastRefresh: "Última actualización",
    accountId: "ID de cuenta",
    organization: "Organización",
    savedAccounts: "Cuentas guardadas",
    savedAccountsSub:
      "Administra aquí las cuentas guardadas, incluyendo cambio, actualización, detalles y eliminación.",
    teamName: "Equipo",
    login: "Inicio de sesión",
    switchBtn: "Cambiar",
    refreshBtn: "Actualizar",
    detailsBtn: "Detalles",
    removeBtn: "Eliminar",
    settingsTitle: "Configuración",
    codexAppRestartTitle: "Política de reinicio de Codex App",
    codexAppRestartSub: "Controla cómo la extensión maneja Codex App cuando ya está en ejecución al cambiar de cuenta.",
    restartModeAuto: "Reiniciar automáticamente",
    restartModeAutoDesc: "Si Codex App ya está en ejecución, reiníciala inmediatamente después de cambiar de cuenta.",
    restartModeManual: "Preguntar cada vez",
    restartModeManualDesc: "Mantén la decisión final en tus manos y confirma cada reinicio manualmente.",
    restartModeNote:
      "La extensión solo reinicia Codex App cuando ya está en ejecución. No iniciará la app de escritorio desde cero.",
    autoRefreshTitle: "Actualización automática",
    autoRefreshSub: "Actualiza las cuotas de las cuentas guardadas de forma periódica.",
    autoRefreshOn: "Activar actualización automática",
    autoRefreshOnDesc: "Actualiza las cuotas de todas las cuentas guardadas en un intervalo fijo.",
    autoRefreshOff: "Desactivado",
    autoRefreshOffDesc: "Desactiva la actualización automática y actualiza manualmente cuando lo necesites.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Actualiza las cuotas de todas las cuentas guardadas cada {value} minutos.",
    autoSwitchTitle: "Cambio automático de cuenta",
    autoSwitchSub: "Cuando la cuota de la cuenta activa sea baja, cambia automáticamente a otra cuenta guardada.",
    autoSwitchOn: "Activar cambio automático",
    autoSwitchOnDesc: "Después de actualizar, intenta cambiar a otra cuenta disponible cuando la cuenta activa alcance tu límite.",
    autoSwitchOff: "Desactivado",
    autoSwitchOffDesc: "Mantén la cuenta actual hasta que cambies manualmente.",
    autoSwitchThresholdSuffix: "umbral de cambio",
    autoSwitchThresholdDescTemplate: "Intentar cambiar cuando la cuota restante de {label} sea de {value}% o menos.",
    autoSwitchAnyNote: "Cualquier umbral activará un intento de cambio.",
    autoSwitchToastSwitched: "La cuota activa alcanzó el umbral de cambio automático. Se cambió a {account}.",
    appPathTitle: "Ruta de Codex App",
    appPathSub:
      "Opcional. Define una ruta personalizada para Codex App o déjala vacía para usar la detección automática.",
    appPathEmpty: "No se detectó ninguna ruta de inicio. Selecciónala manualmente.",
    pickPath: "Elegir ruta",
    clearPath: "Ruta auto detectada",
    dashboardSettingsTitle: "Vista del panel",
    dashboardSettingsSub: "Controla qué muestra el panel de cuotas.",
    showReviewOn: "Mostrar cuota de Code Review",
    showReviewOnDesc: "Muestra la cuota de Code Review en el panel y en las tarjetas de cuenta.",
    showReviewOff: "Ocultar cuota de Code Review",
    showReviewOffDesc: "Simplifica el panel mostrando solo las cuotas de 5 horas y semanales.",
    warningTitle: "Alerta de cuota",
    warningSub: "Muestra una advertencia cuando la cuota restante de 5 horas o semanal de la cuenta activa cae por debajo del umbral.",
    warningOn: "Activar alerta",
    warningOnDesc: "Muestra notificaciones tras actualizar si la cuota restante de 5 horas o la semanal queda por debajo del umbral.",
    warningOff: "Desactivar alerta",
    warningOffDesc: "No mostrar notificaciones por umbral de cuota.",
    warningValueDescTemplate: "Avisar cuando la cuota disponible baje de {value}%.",
    colorThresholdTitle: "Umbrales de color",
    colorThresholdSub: "Controla cuándo las cuotas se muestran en verde, amarillo o rojo.",
    colorThresholdGreenTitle: "El verde empieza en",
    colorThresholdYellowTitle: "El amarillo empieza en",
    colorThresholdGreenDescTemplate: "Muestra verde cuando la cuota disponible sea al menos de {value}%.",
    colorThresholdYellowDescTemplate:
      "Muestra amarillo cuando la cuota disponible sea al menos de {value}% y esté por debajo del umbral verde.",
    colorThresholdRedNoteTemplate: "Muestra rojo cuando la cuota disponible caiga por debajo de {value}%.",
    debugTitle: "Registros de depuración",
    debugSub: "Controla si los resúmenes de solicitudes se escriben en el panel de salida.",
    debugOn: "Activar registros de depuración",
    debugOnDesc: "Registra resultados saneados para ayudar a diagnosticar problemas de API.",
    debugOff: "Desactivar registros de depuración",
    debugOffDesc: "Desactivado por defecto para evitar ruido innecesario.",
    debugNote:
      "Los registros se escriben en el canal `Codex Accounts Network` con truncado y redacción de datos sensibles.",
    languageTitle: "Idioma",
    languageSub: "Sobrescribe el idioma del panel y los avisos solo para esta extensión.",
    languageAuto: "Automático (seguir VS Code)",
    languageZh: "Chino simplificado",
    languageEn: "English",
    languageNote: "Los cambios se aplican de inmediato solo a esta extensión y no afectan a otras partes de VS Code.",
    statusShort: "Estado",
    statusToggleTip: "Controla si esta cuenta aparece en la ventana emergente inferior de estado",
    statusToggleTipChecked:
      "Esta cuenta ya se muestra en la ventana emergente inferior de estado. Haz clic para quitarla",
    statusLimitTip: "La ventana emergente de estado puede mostrar como máximo 2 cuentas extra. Quita una primero",
    unknown: "desconocido",
    never: "nunca",
    resetUnknown: "reinicio desconocido"
  },
  de: {
    panelTitle: "Codex Accounts Manager Kontingentübersicht",
    brandSub: "Hauptdashboard für Kontowechsel und Kontingentüberwachung",
    refreshPage: "Seite aktualisieren",
    addAccount: "Konto hinzufügen",
    importCurrent: "Aktuelles Konto importieren",
    refreshAll: "Kontingente aktualisieren",
    dashboardTitle: "Codex Accounts Manager · Kontingent-Dashboard",
    dashboardSub: "Hauptdashboard für Überwachung, Verwaltung und Screenshots",
    empty: "Noch keine gespeicherten Konten",
    noActiveAccountTitle: "Kein aktives Konto",
    noActiveAccountSub: "Es gibt gespeicherte Konten, aber derzeit ist keines als aktiv markiert.",
    current: "Aktuell",
    hourlyLabel: "5 Std.",
    weeklyLabel: "Wöchentlich",
    reviewLabel: "Review",
    userId: "Benutzer-ID",
    lastRefresh: "Letzte Aktualisierung",
    accountId: "Konto-ID",
    organization: "Organisation",
    savedAccounts: "Gespeicherte Konten",
    savedAccountsSub:
      "Verwalte hier gespeicherte Konten, einschließlich Wechsel, Aktualisierung, Details und Entfernung.",
    teamName: "Team",
    login: "Anmeldung",
    switchBtn: "Wechseln",
    refreshBtn: "Aktualisieren",
    detailsBtn: "Details",
    removeBtn: "Entfernen",
    settingsTitle: "Einstellungen",
    codexAppRestartTitle: "Codex-App-Neustart",
    codexAppRestartSub: "Steuert, wie die Erweiterung mit einer bereits laufenden Codex App beim Kontowechsel umgeht.",
    restartModeAuto: "Automatisch neu starten",
    restartModeAutoDesc: "Wenn Codex App bereits läuft, wird sie nach dem Kontowechsel sofort neu gestartet.",
    restartModeManual: "Jedes Mal fragen",
    restartModeManualDesc: "Die endgültige Entscheidung bleibt bei dir und jeder Neustart wird manuell bestätigt.",
    restartModeNote:
      "Die Erweiterung startet Codex App nur neu, wenn sie bereits läuft. Sie startet die Desktop-App nicht aus einem gestoppten Zustand.",
    autoRefreshTitle: "Automatische Aktualisierung",
    autoRefreshSub: "Aktualisiert die Kontingente gespeicherter Konten in festgelegten Intervallen.",
    autoRefreshOn: "Automatische Aktualisierung aktivieren",
    autoRefreshOnDesc: "Aktualisiert die Kontingente aller gespeicherten Konten in einem festen Zeitplan.",
    autoRefreshOff: "Aus",
    autoRefreshOffDesc: "Deaktiviert die zeitgesteuerte Aktualisierung und aktualisiert nur manuell bei Bedarf.",
    autoRefreshValueTemplate: "{value} Min.",
    autoRefreshValueDescTemplate: "Aktualisiert die Kontingente aller gespeicherten Konten alle {value} Minuten.",
    autoSwitchTitle: "Automatischer Kontowechsel",
    autoSwitchSub: "Wenn das Kontingent des aktiven Kontos niedrig wird, wechsle automatisch zu einem anderen gespeicherten Konto.",
    autoSwitchOn: "Automatischen Wechsel aktivieren",
    autoSwitchOnDesc:
      "Versucht nach dem Aktualisieren zu einem anderen verfügbaren Konto zu wechseln, wenn das aktive Konto deinen Grenzwert erreicht.",
    autoSwitchOff: "Aus",
    autoSwitchOffDesc: "Das aktuelle Konto bleibt aktiv, bis du manuell wechselst.",
    autoSwitchThresholdSuffix: "Wechselschwelle",
    autoSwitchThresholdDescTemplate:
      "Wechsel versuchen, wenn das verbleibende {label}-Kontingent bei {value}% oder weniger liegt.",
    autoSwitchAnyNote: "Jeder erreichte Schwellenwert löst einen Wechselversuch aus.",
    autoSwitchToastSwitched:
      "Das aktive Kontingent hat die automatische Wechselschwelle erreicht. Zu {account} gewechselt.",
    appPathTitle: "Codex-App-Pfad",
    appPathSub:
      "Optional. Lege einen benutzerdefinierten Pfad zur Codex App fest oder lasse das Feld leer für die automatische Erkennung.",
    appPathEmpty: "Kein Startpfad erkannt. Bitte manuell auswählen.",
    pickPath: "Pfad auswählen",
    clearPath: "Automatisch erkannter Pfad",
    dashboardSettingsTitle: "Dashboard-Anzeige",
    dashboardSettingsSub: "Steuert, welche Informationen im Kontingent-Dashboard angezeigt werden.",
    showReviewOn: "Code-Review-Kontingent anzeigen",
    showReviewOnDesc: "Zeigt das Code-Review-Kontingent im Dashboard und in den Kontokarten an.",
    showReviewOff: "Code-Review-Kontingent ausblenden",
    showReviewOffDesc: "Vereinfacht das Dashboard und zeigt nur 5-Stunden- und Wochenkontingente an.",
    warningTitle: "Kontingentwarnung",
    warningSub: "Zeigt eine Warnung an, wenn das verbleibende 5-Stunden- oder Wochenkontingent des aktiven Kontos unter den Schwellenwert fällt.",
    warningOn: "Warnung aktivieren",
    warningOnDesc:
      "Zeigt nach dem Aktualisieren Benachrichtigungen an, wenn entweder das verbleibende 5-Stunden- oder Wochenkontingent unter dem Schwellenwert liegt.",
    warningOff: "Warnung deaktivieren",
    warningOffDesc: "Keine Benachrichtigungen bei Unterschreitung des Kontingentschwellenwerts anzeigen.",
    warningValueDescTemplate: "Warnen, wenn das verfügbare Kontingent unter {value}% fällt.",
    colorThresholdTitle: "Farbgrenzen",
    colorThresholdSub: "Steuert, wann Kontingente grün, gelb oder rot angezeigt werden.",
    colorThresholdGreenTitle: "Grün beginnt bei",
    colorThresholdYellowTitle: "Gelb beginnt bei",
    colorThresholdGreenDescTemplate: "Zeigt Grün an, wenn das verfügbare Kontingent mindestens {value}% beträgt.",
    colorThresholdYellowDescTemplate:
      "Zeigt Gelb an, wenn das verfügbare Kontingent mindestens {value}% beträgt und unter dem grünen Schwellenwert liegt.",
    colorThresholdRedNoteTemplate: "Zeigt Rot an, wenn das verfügbare Kontingent unter {value}% fällt.",
    debugTitle: "Netzwerk-Debug-Logs",
    debugSub: "Steuert, ob Anforderungszusammenfassungen in das Ausgabefenster geschrieben werden.",
    debugOn: "Debug-Logs aktivieren",
    debugOnDesc: "Protokolliert bereinigte Anforderungsergebnisse zur Diagnose von API-Problemen.",
    debugOff: "Debug-Logs deaktivieren",
    debugOffDesc: "Standardmäßig deaktiviert, um unnötige Debug-Ausgaben zu vermeiden.",
    debugNote:
      "Logs werden in den Ausgabekanal `Codex Accounts Network` geschrieben, wobei sensible Daten gekürzt und maskiert werden.",
    languageTitle: "Sprache",
    languageSub: "Überschreibt die Sprache von Dashboard und Hinweisen nur für diese Erweiterung.",
    languageAuto: "Automatisch (VS Code folgen)",
    languageZh: "Vereinfachtes Chinesisch",
    languageEn: "English",
    languageNote:
      "Änderungen gelten sofort nur für diese Erweiterung und beeinflussen die übrige VS-Code-Oberfläche nicht.",
    statusShort: "Status",
    statusToggleTip: "Steuert, ob dieses Konto im unteren Status-Popup erscheint",
    statusToggleTipChecked: "Dieses Konto wird bereits im unteren Status-Popup angezeigt. Zum Entfernen klicken",
    statusLimitTip: "Im Status-Popup können höchstens 2 zusätzliche Konten angezeigt werden. Entferne zuerst eines",
    unknown: "unbekannt",
    never: "nie",
    resetUnknown: "Zurücksetzung unbekannt"
  },
  fr: {
    panelTitle: "Résumé des quotas Codex Accounts Manager",
    brandSub: "Tableau de bord principal pour changer de compte et surveiller les quotas",
    refreshPage: "Actualiser la page",
    addAccount: "Ajouter un compte",
    importCurrent: "Importer le compte actuel",
    refreshAll: "Actualiser les quotas",
    dashboardTitle: "Codex Accounts Manager · Tableau de bord des quotas",
    dashboardSub: "Vue principale pour le suivi, la gestion et les captures",
    empty: "Aucun compte enregistré pour le moment",
    noActiveAccountTitle: "Aucun compte actif",
    noActiveAccountSub: "Des comptes enregistrés existent, mais aucun n’est actuellement marqué comme actif.",
    current: "Actuel",
    hourlyLabel: "5 h",
    weeklyLabel: "Hebdo",
    reviewLabel: "Revue",
    userId: "ID utilisateur",
    lastRefresh: "Dernière actualisation",
    accountId: "ID du compte",
    organization: "Organisation",
    savedAccounts: "Comptes enregistrés",
    savedAccountsSub:
      "Gérez ici les comptes enregistrés, y compris le changement, l’actualisation, les détails et la suppression.",
    teamName: "Équipe",
    login: "Connexion",
    switchBtn: "Basculer",
    refreshBtn: "Actualiser",
    detailsBtn: "Détails",
    removeBtn: "Supprimer",
    settingsTitle: "Paramètres",
    codexAppRestartTitle: "Politique de redémarrage Codex App",
    codexAppRestartSub:
      "Contrôle la façon dont l’extension gère Codex App lorsqu’elle est déjà en cours d’exécution au changement de compte.",
    restartModeAuto: "Redémarrer automatiquement",
    restartModeAutoDesc: "Si Codex App est déjà lancée, elle redémarre immédiatement après le changement de compte.",
    restartModeManual: "Demander à chaque fois",
    restartModeManualDesc: "Vous gardez la décision finale et confirmez chaque redémarrage manuellement.",
    restartModeNote:
      "L’extension redémarre Codex App uniquement lorsqu’elle est déjà en cours d’exécution. Elle ne lance pas l’application depuis un état arrêté.",
    autoRefreshTitle: "Actualisation automatique",
    autoRefreshSub: "Actualise périodiquement les quotas des comptes enregistrés.",
    autoRefreshOn: "Activer l’actualisation automatique",
    autoRefreshOnDesc: "Actualise les quotas de tous les comptes enregistrés selon un intervalle fixe.",
    autoRefreshOff: "Désactivé",
    autoRefreshOffDesc: "Désactive l’actualisation planifiée et laisse l’actualisation manuelle.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Actualise les quotas de tous les comptes enregistrés toutes les {value} minutes.",
    autoSwitchTitle: "Bascule automatique de compte",
    autoSwitchSub: "Quand le quota du compte actif devient faible, bascule automatiquement vers un autre compte enregistré.",
    autoSwitchOn: "Activer la bascule automatique",
    autoSwitchOnDesc:
      "Après actualisation, tente de passer à un autre compte disponible lorsque le compte actif atteint ta limite.",
    autoSwitchOff: "Désactivé",
    autoSwitchOffDesc: "Garde le compte actuel jusqu’à un changement manuel.",
    autoSwitchThresholdSuffix: "seuil de bascule",
    autoSwitchThresholdDescTemplate:
      "Essayer de basculer lorsque le quota restant {label} est inférieur ou égal à {value}%.",
    autoSwitchAnyNote: "N’importe quel seuil atteint déclenche une tentative de bascule.",
    autoSwitchToastSwitched: "Le quota actif a atteint le seuil de bascule automatique. Bascule vers {account}.",
    appPathTitle: "Chemin de Codex App",
    appPathSub:
      "Optionnel. Définissez un chemin personnalisé pour Codex App ou laissez vide pour utiliser la détection automatique.",
    appPathEmpty: "Aucun chemin de lancement détecté. Veuillez le choisir manuellement.",
    pickPath: "Choisir un chemin",
    clearPath: "Chemin détecté automatiquement",
    dashboardSettingsTitle: "Affichage du tableau de bord",
    dashboardSettingsSub: "Contrôle les informations affichées dans le tableau de bord des quotas.",
    showReviewOn: "Afficher le quota Code Review",
    showReviewOnDesc: "Affiche le quota Code Review dans le tableau de bord et les cartes de compte.",
    showReviewOff: "Masquer le quota Code Review",
    showReviewOffDesc: "Allège le tableau de bord en n’affichant que les quotas 5 heures et hebdomadaire.",
    warningTitle: "Alerte de quota",
    warningSub: "Affiche une alerte lorsque le quota restant sur 5 heures ou hebdomadaire du compte actif passe sous le seuil.",
    warningOn: "Activer l’alerte",
    warningOnDesc: "Affiche des notifications après actualisation si le quota restant sur 5 heures ou hebdomadaire passe sous le seuil.",
    warningOff: "Désactiver l’alerte",
    warningOffDesc: "N’affiche pas de notifications liées au seuil de quota.",
    warningValueDescTemplate: "Alerter lorsque le quota disponible descend sous {value}%.",
    colorThresholdTitle: "Seuils de couleur",
    colorThresholdSub: "Contrôle quand les quotas apparaissent en vert, jaune ou rouge.",
    colorThresholdGreenTitle: "Le vert commence à",
    colorThresholdYellowTitle: "Le jaune commence à",
    colorThresholdGreenDescTemplate: "Affiche le vert lorsque le quota disponible est d’au moins {value}%.",
    colorThresholdYellowDescTemplate:
      "Affiche le jaune lorsque le quota disponible est d’au moins {value}% et reste sous le seuil vert.",
    colorThresholdRedNoteTemplate: "Affiche le rouge lorsque le quota disponible descend sous {value}%.",
    debugTitle: "Journaux réseau",
    debugSub: "Contrôle si les résumés de requêtes sont écrits dans le panneau de sortie.",
    debugOn: "Activer les journaux de débogage",
    debugOnDesc: "Enregistre des résultats nettoyés pour faciliter le diagnostic des problèmes d’API.",
    debugOff: "Désactiver les journaux de débogage",
    debugOffDesc: "Désactivé par défaut pour éviter du bruit inutile.",
    debugNote:
      "Les journaux sont écrits dans le canal `Codex Accounts Network` avec troncature et masquage des données sensibles.",
    languageTitle: "Langue",
    languageSub: "Remplace la langue du tableau de bord et des messages uniquement pour cette extension.",
    languageAuto: "Automatique (suivre VS Code)",
    languageZh: "Chinois simplifié",
    languageEn: "English",
    languageNote:
      "Les changements s'appliquent immédiatement à cette extension uniquement et n'affectent pas le reste de VS Code.",
    statusShort: "Statut",
    statusToggleTip: "Contrôle si ce compte apparaît dans la fenêtre de statut en bas",
    statusToggleTipChecked: "Ce compte est déjà affiché dans la fenêtre de statut en bas. Cliquez pour le retirer",
    statusLimitTip: "La fenêtre de statut peut afficher au maximum 2 comptes supplémentaires. Retirez-en un d’abord",
    unknown: "inconnu",
    never: "jamais",
    resetUnknown: "réinitialisation inconnue"
  },
  "pt-br": {
    panelTitle: "Resumo de cotas do Codex Accounts Manager",
    brandSub: "Painel principal para alternar contas e monitorar cotas",
    refreshPage: "Atualizar página",
    addAccount: "Adicionar conta",
    importCurrent: "Importar conta atual",
    refreshAll: "Atualizar cotas",
    dashboardTitle: "Codex Accounts Manager · Painel de cotas",
    dashboardSub: "Painel principal para monitoramento, gestão e capturas",
    empty: "Ainda não há contas salvas",
    noActiveAccountTitle: "Nenhuma conta ativa",
    noActiveAccountSub: "Existem contas salvas, mas nenhuma está marcada como ativa no momento.",
    current: "Atual",
    hourlyLabel: "5 h",
    weeklyLabel: "Semanal",
    reviewLabel: "Revisão",
    userId: "ID do usuário",
    lastRefresh: "Última atualização",
    accountId: "ID da conta",
    organization: "Organização",
    savedAccounts: "Contas salvas",
    savedAccountsSub: "Gerencie aqui as contas salvas, incluindo troca, atualização, detalhes e remoção.",
    teamName: "Equipe",
    login: "Login",
    switchBtn: "Alternar",
    refreshBtn: "Atualizar",
    detailsBtn: "Detalhes",
    removeBtn: "Remover",
    settingsTitle: "Configurações",
    codexAppRestartTitle: "Política de reinício do Codex App",
    codexAppRestartSub:
      "Controla como a extensão lida com o Codex App quando ele já está em execução ao trocar de conta.",
    restartModeAuto: "Reiniciar automaticamente",
    restartModeAutoDesc: "Se o Codex App já estiver em execução, reinicie-o imediatamente após trocar de conta.",
    restartModeManual: "Perguntar sempre",
    restartModeManualDesc: "Mantenha a decisão final nas suas mãos e confirme cada reinício manualmente.",
    restartModeNote:
      "A extensão só reinicia o Codex App quando ele já está em execução. Ela não abrirá o app de desktop a partir de um estado parado.",
    autoRefreshTitle: "Atualização automática",
    autoRefreshSub: "Atualiza periodicamente as cotas das contas salvas.",
    autoRefreshOn: "Ativar atualização automática",
    autoRefreshOnDesc: "Atualiza as cotas de todas as contas salvas em um intervalo fixo.",
    autoRefreshOff: "Desativado",
    autoRefreshOffDesc: "Desativa a atualização agendada e deixa a atualização manual.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Atualiza as cotas de todas as contas salvas a cada {value} minutos.",
    autoSwitchTitle: "Troca automática de conta",
    autoSwitchSub: "Quando a cota da conta ativa ficar baixa, altere automaticamente para outra conta salva.",
    autoSwitchOn: "Ativar troca automática",
    autoSwitchOnDesc:
      "Depois da atualização, tenta mudar para outra conta disponível quando a conta ativa atingir o seu limite.",
    autoSwitchOff: "Desativado",
    autoSwitchOffDesc: "Mantém a conta atual até que você troque manualmente.",
    autoSwitchThresholdSuffix: "limite de troca",
    autoSwitchThresholdDescTemplate: "Tentar trocar quando a cota restante de {label} estiver em {value}% ou menos.",
    autoSwitchAnyNote: "Qualquer limite atingido dispara uma tentativa de troca.",
    autoSwitchToastSwitched: "A cota ativa atingiu o limite de troca automática. Conta alterada para {account}.",
    appPathTitle: "Caminho do Codex App",
    appPathSub:
      "Opcional. Defina um caminho personalizado para o Codex App ou deixe em branco para usar a detecção automática.",
    appPathEmpty: "Nenhum caminho de inicialização foi detectado. Escolha um manualmente.",
    pickPath: "Escolher caminho",
    clearPath: "Caminho detectado automaticamente",
    dashboardSettingsTitle: "Exibição do painel",
    dashboardSettingsSub: "Controla quais informações o painel de cotas exibe.",
    showReviewOn: "Mostrar cota de Code Review",
    showReviewOnDesc: "Exibe a cota de Code Review no painel e nos cartões de conta.",
    showReviewOff: "Ocultar cota de Code Review",
    showReviewOffDesc: "Simplifica o painel mostrando apenas as cotas de 5 horas e semanal.",
    warningTitle: "Alerta de cota",
    warningSub: "Mostra um alerta quando a cota restante de 5 horas ou semanal da conta ativa cai abaixo do limite.",
    warningOn: "Ativar alerta",
    warningOnDesc: "Mostra notificações após atualizar se a cota restante de 5 horas ou a semanal estiver abaixo do limite.",
    warningOff: "Desativar alerta",
    warningOffDesc: "Não mostrar notificações de limite de cota.",
    warningValueDescTemplate: "Alertar quando a cota disponível cair abaixo de {value}%.",
    colorThresholdTitle: "Limites de cor",
    colorThresholdSub: "Controla quando as cotas aparecem em verde, amarelo ou vermelho.",
    colorThresholdGreenTitle: "Verde começa em",
    colorThresholdYellowTitle: "Amarelo começa em",
    colorThresholdGreenDescTemplate: "Mostra verde quando a cota disponível for de pelo menos {value}%.",
    colorThresholdYellowDescTemplate:
      "Mostra amarelo quando a cota disponível for de pelo menos {value}% e estiver abaixo do limite verde.",
    colorThresholdRedNoteTemplate: "Mostra vermelho quando a cota disponível cair abaixo de {value}%.",
    debugTitle: "Logs de depuração",
    debugSub: "Controla se os resumos das requisições são escritos no painel de saída.",
    debugOn: "Ativar logs de depuração",
    debugOnDesc: "Registra resultados saneados para ajudar a diagnosticar problemas de API.",
    debugOff: "Desativar logs de depuração",
    debugOffDesc: "Desativado por padrão para evitar ruído desnecessário.",
    debugNote:
      "Os logs são escritos no canal `Codex Accounts Network`, com truncamento e ocultação de dados sensíveis.",
    languageTitle: "Idioma",
    languageSub: "Substitui o idioma do painel e das mensagens apenas para esta extensão.",
    languageAuto: "Automático (seguir o VS Code)",
    languageZh: "Chinês simplificado",
    languageEn: "English",
    languageNote:
      "As alterações são aplicadas imediatamente apenas a esta extensão e não afetam o restante da interface do VS Code.",
    statusShort: "Status",
    statusToggleTip: "Controla se esta conta aparece no pop-up inferior da barra de status",
    statusToggleTipChecked: "Esta conta já aparece no pop-up inferior da barra de status. Clique para remover",
    statusLimitTip: "O pop-up da barra de status pode mostrar no máximo 2 contas extras. Desmarque uma primeiro",
    unknown: "desconhecido",
    never: "nunca",
    resetUnknown: "reinício desconhecido"
  },
  ru: {
    panelTitle: "Сводка квот Codex Accounts Manager",
    brandSub: "Главная панель для переключения аккаунтов и контроля квот",
    refreshPage: "Обновить страницу",
    addAccount: "Добавить аккаунт",
    importCurrent: "Импортировать текущий аккаунт",
    refreshAll: "Обновить квоты",
    dashboardTitle: "Codex Accounts Manager · Панель квот",
    dashboardSub: "Основная панель для мониторинга, управления и скриншотов",
    empty: "Сохраненных аккаунтов пока нет",
    noActiveAccountTitle: "Нет активного аккаунта",
    noActiveAccountSub: "Сохраненные аккаунты есть, но ни один из них сейчас не помечен как активный.",
    current: "Текущий",
    hourlyLabel: "5 ч",
    weeklyLabel: "Неделя",
    reviewLabel: "Ревью",
    userId: "ID пользователя",
    lastRefresh: "Последнее обновление",
    accountId: "ID аккаунта",
    organization: "Организация",
    savedAccounts: "Сохраненные аккаунты",
    savedAccountsSub: "Управляйте сохраненными аккаунтами здесь: переключение, обновление, детали и удаление.",
    teamName: "Команда",
    login: "Вход",
    switchBtn: "Переключить",
    refreshBtn: "Обновить",
    detailsBtn: "Подробнее",
    removeBtn: "Удалить",
    settingsTitle: "Настройки",
    codexAppRestartTitle: "Политика перезапуска Codex App",
    codexAppRestartSub:
      "Определяет, как расширение должно работать с уже запущенным Codex App при переключении аккаунта.",
    restartModeAuto: "Перезапускать автоматически",
    restartModeAutoDesc: "Если Codex App уже запущен, перезапускать его сразу после смены аккаунта.",
    restartModeManual: "Спрашивать каждый раз",
    restartModeManualDesc: "Оставляет окончательное решение за вами и требует подтверждения каждого перезапуска.",
    restartModeNote:
      "Расширение перезапускает Codex App только если он уже запущен. Оно не будет запускать десктопное приложение из остановленного состояния.",
    autoRefreshTitle: "Автообновление квот",
    autoRefreshSub: "Периодически обновляет квоты сохраненных аккаунтов.",
    autoRefreshOn: "Включить автообновление",
    autoRefreshOnDesc: "Обновляет квоты всех сохраненных аккаунтов через фиксированные интервалы.",
    autoRefreshOff: "Выключено",
    autoRefreshOffDesc: "Отключает автоматическое обновление и оставляет только ручное.",
    autoRefreshValueTemplate: "{value} мин",
    autoRefreshValueDescTemplate: "Обновлять квоты всех сохраненных аккаунтов каждые {value} минут.",
    autoSwitchTitle: "Автопереключение аккаунта",
    autoSwitchSub: "Когда квота активного аккаунта становится низкой, автоматически переключайтесь на другой сохранённый аккаунт.",
    autoSwitchOn: "Включить автопереключение",
    autoSwitchOnDesc:
      "После обновления пытается переключиться на другой доступный аккаунт, когда активный аккаунт достигает вашего порога.",
    autoSwitchOff: "Выключено",
    autoSwitchOffDesc: "Оставляет текущий аккаунт активным, пока вы не переключите его вручную.",
    autoSwitchThresholdSuffix: "порог переключения",
    autoSwitchThresholdDescTemplate:
      "Пытаться переключиться, когда оставшаяся квота {label} составляет {value}% или меньше.",
    autoSwitchAnyNote: "Достаточно срабатывания любого порога, чтобы попробовать переключение.",
    autoSwitchToastSwitched:
      "Квота активного аккаунта достигла порога автопереключения. Выполнено переключение на {account}.",
    appPathTitle: "Путь к Codex App",
    appPathSub: "Необязательно. Укажите пользовательский путь к Codex App или оставьте пустым для автоопределения.",
    appPathEmpty: "Путь запуска не найден. Выберите его вручную.",
    pickPath: "Выбрать путь",
    clearPath: "Автоопределяемый путь",
    dashboardSettingsTitle: "Вид панели",
    dashboardSettingsSub: "Определяет, какая информация отображается на панели квот.",
    showReviewOn: "Показывать квоту Code Review",
    showReviewOnDesc: "Показывает квоту Code Review на панели и в карточках аккаунтов.",
    showReviewOff: "Скрывать квоту Code Review",
    showReviewOffDesc: "Упрощает панель, оставляя только 5-часовую и недельную квоты.",
    warningTitle: "Предупреждение о квоте",
    warningSub: "Показывает предупреждение, когда остаток 5-часовой или недельной квоты активного аккаунта падает ниже порога.",
    warningOn: "Включить предупреждение",
    warningOnDesc: "Показывает уведомления после обновления, если остаток 5-часовой или недельной квоты оказывается ниже заданного порога.",
    warningOff: "Отключить предупреждение",
    warningOffDesc: "Не показывать уведомления о порогах квоты.",
    warningValueDescTemplate: "Предупреждать, когда доступная квота падает ниже {value}%.",
    colorThresholdTitle: "Цветовые пороги",
    colorThresholdSub: "Определяет, когда квоты показываются зелёным, жёлтым или красным цветом.",
    colorThresholdGreenTitle: "Зелёный начинается с",
    colorThresholdYellowTitle: "Жёлтый начинается с",
    colorThresholdGreenDescTemplate: "Показывать зелёный цвет, когда доступная квота не ниже {value}%.",
    colorThresholdYellowDescTemplate:
      "Показывать жёлтый цвет, когда доступная квота не ниже {value}% и ниже зелёного порога.",
    colorThresholdRedNoteTemplate: "Показывать красный цвет, когда доступная квота ниже {value}%.",
    debugTitle: "Сетевые журналы отладки",
    debugSub: "Определяет, записываются ли сводки запросов в панель вывода.",
    debugOn: "Включить журналы отладки",
    debugOnDesc: "Записывает очищенные результаты запросов для диагностики проблем API.",
    debugOff: "Выключить журналы отладки",
    debugOffDesc: "По умолчанию отключено, чтобы избежать лишнего отладочного шума.",
    debugNote:
      "Журналы записываются в канал `Codex Accounts Network`, при этом чувствительные данные сокращаются и маскируются.",
    languageTitle: "Язык",
    languageSub: "Переопределяет язык панели и уведомлений только для этого расширения.",
    languageAuto: "Авто (следовать VS Code)",
    languageZh: "Упрощенный китайский",
    languageEn: "English",
    languageNote: "Изменения применяются сразу только к этому расширению и не влияют на остальной интерфейс VS Code.",
    statusShort: "Статус",
    statusToggleTip: "Управляет тем, показывается ли этот аккаунт во всплывающем окне строки состояния внизу",
    statusToggleTipChecked:
      "Этот аккаунт уже отображается во всплывающем окне строки состояния внизу. Нажмите, чтобы убрать",
    statusLimitTip:
      "Во всплывающем окне строки состояния можно показать максимум 2 дополнительных аккаунта. Сначала уберите один",
    unknown: "неизвестно",
    never: "никогда",
    resetUnknown: "время сброса неизвестно"
  },
  ko: {
    panelTitle: "Codex Accounts Manager 할당량 요약",
    brandSub: "다중 계정 전환과 할당량 모니터링을 위한 메인 대시보드",
    refreshPage: "페이지 새로고침",
    addAccount: "계정 추가",
    importCurrent: "현재 계정 가져오기",
    refreshAll: "할당량 새로고침",
    dashboardTitle: "Codex Accounts Manager · 할당량 대시보드",
    dashboardSub: "모니터링, 관리, 스크린샷에 적합한 메인 대시보드",
    empty: "저장된 계정이 없습니다",
    noActiveAccountTitle: "활성 계정이 없습니다",
    noActiveAccountSub: "저장된 계정은 있지만 현재 활성으로 표시된 계정이 없습니다.",
    current: "현재",
    hourlyLabel: "5시간",
    weeklyLabel: "주간",
    reviewLabel: "리뷰",
    userId: "사용자 ID",
    lastRefresh: "최근 새로고침",
    accountId: "계정 ID",
    organization: "조직",
    savedAccounts: "저장된 계정",
    savedAccountsSub: "저장된 계정을 여기서 관리하고 전환, 새로고침, 상세 보기, 삭제를 할 수 있습니다.",
    teamName: "팀",
    login: "로그인",
    switchBtn: "전환",
    refreshBtn: "새로고침",
    detailsBtn: "상세",
    removeBtn: "삭제",
    settingsTitle: "설정",
    codexAppRestartTitle: "Codex App 재시작 정책",
    codexAppRestartSub: "계정 전환 시 현재 실행 중인 Codex App을 어떻게 처리할지 제어합니다.",
    restartModeAuto: "자동으로 재시작",
    restartModeAutoDesc: "Codex App이 이미 실행 중이면 계정 전환 후 즉시 재시작합니다.",
    restartModeManual: "매번 수동으로 확인",
    restartModeManualDesc: "최종 결정권을 유지하고 매번 재시작을 확인합니다.",
    restartModeNote: "Codex App이 이미 실행 중일 때만 재시작합니다. 꺼진 상태에서는 앱을 강제로 실행하지 않습니다.",
    autoRefreshTitle: "자동 새로고침",
    autoRefreshSub: "저장된 계정의 할당량 데이터를 주기적으로 새로고침합니다.",
    autoRefreshOn: "자동 새로고침 켜기",
    autoRefreshOnDesc: "저장된 모든 계정의 할당량을 고정된 간격으로 새로고침합니다.",
    autoRefreshOff: "끄기",
    autoRefreshOffDesc: "자동 새로고침을 끄고 필요할 때만 수동으로 새로고침합니다.",
    autoRefreshValueTemplate: "{value}분",
    autoRefreshValueDescTemplate: "저장된 모든 계정의 할당량을 {value}분마다 새로고침합니다.",
    autoSwitchTitle: "자동 계정 전환",
    autoSwitchSub: "활성 계정의 할당량이 낮아지면 다른 저장된 계정으로 자동 전환합니다.",
    autoSwitchOn: "자동 전환 켜기",
    autoSwitchOnDesc: "새로고침 후 현재 계정이 임계값에 도달하면 다른 사용 가능한 계정으로 전환을 시도합니다.",
    autoSwitchOff: "끄기",
    autoSwitchOffDesc: "수동으로 바꿀 때까지 현재 계정을 유지합니다.",
    autoSwitchThresholdSuffix: "전환 임계값",
    autoSwitchThresholdDescTemplate: "{label} 남은 할당량이 {value}% 이하가 되면 전환을 시도합니다.",
    autoSwitchAnyNote: "둘 중 하나의 임계값에 도달하면 전환을 시도합니다.",
    autoSwitchToastSwitched: "활성 할당량이 자동 전환 임계값에 도달해 {account}(으)로 전환했습니다.",
    appPathTitle: "Codex App 경로",
    appPathSub: "선택 사항입니다. Codex App의 사용자 지정 경로를 지정하거나 비워 두어 자동 감지를 사용하세요.",
    appPathEmpty: "실행 경로를 찾지 못했습니다. 수동으로 선택해 주세요.",
    pickPath: "경로 선택",
    clearPath: "자동 감지 경로",
    dashboardSettingsTitle: "대시보드 표시",
    dashboardSettingsSub: "할당량 대시보드에 어떤 정보를 표시할지 제어합니다.",
    showReviewOn: "Code Review 할당량 표시",
    showReviewOnDesc: "대시보드와 계정 카드에 Code Review 할당량을 표시합니다.",
    showReviewOff: "Code Review 할당량 숨기기",
    showReviewOffDesc: "5시간 및 주간 할당량만 표시하여 대시보드를 더 단순하게 유지합니다.",
    warningTitle: "할당량 경고",
    warningSub: "활성 계정의 5시간 또는 주간 남은 할당량이 임계값 아래로 떨어지면 경고를 표시합니다.",
    warningOn: "경고 켜기",
    warningOnDesc: "새로고침 후 5시간 또는 주간 남은 할당량 중 하나가 임계값보다 낮으면 알림을 표시합니다.",
    warningOff: "경고 끄기",
    warningOffDesc: "할당량 임계값 알림을 표시하지 않습니다.",
    warningValueDescTemplate: "사용 가능한 할당량이 {value}% 아래로 떨어지면 경고합니다.",
    colorThresholdTitle: "색상 임계값",
    colorThresholdSub: "할당량이 녹색, 노란색, 빨간색으로 표시되는 기준을 제어합니다.",
    colorThresholdGreenTitle: "녹색 시작값",
    colorThresholdYellowTitle: "노란색 시작값",
    colorThresholdGreenDescTemplate: "사용 가능한 할당량이 {value}% 이상이면 녹색으로 표시합니다.",
    colorThresholdYellowDescTemplate:
      "사용 가능한 할당량이 {value}% 이상이고 녹색 임계값보다 낮으면 노란색으로 표시합니다.",
    colorThresholdRedNoteTemplate: "사용 가능한 할당량이 {value}% 미만이면 빨간색으로 표시합니다.",
    debugTitle: "네트워크 디버그 로그",
    debugSub: "요청 요약을 출력 패널에 기록할지 제어합니다.",
    debugOn: "디버그 로그 켜기",
    debugOnDesc: "정리된 요청 결과를 기록해 API 문제를 진단하는 데 도움을 줍니다.",
    debugOff: "디버그 로그 끄기",
    debugOffDesc: "불필요한 디버그 출력을 피하기 위해 기본적으로 꺼져 있습니다.",
    debugNote: "로그는 `Codex Accounts Network` 출력 채널에 기록되며 민감한 데이터는 잘리거나 가려집니다.",
    languageTitle: "언어",
    languageSub: "이 확장에 대해서만 대시보드와 알림 언어를 덮어씁니다.",
    languageAuto: "자동 (VS Code 따름)",
    languageZh: "중국어 간체",
    languageEn: "English",
    languageNote: "변경 사항은 이 확장에만 즉시 적용되며 VS Code의 다른 UI 언어에는 영향을 주지 않습니다.",
    statusShort: "상태",
    statusToggleTip: "이 계정을 하단 상태 표시 팝업에 표시할지 제어합니다",
    statusToggleTipChecked: "이 계정은 이미 하단 상태 표시 팝업에 표시되고 있습니다. 클릭하면 제거합니다",
    statusLimitTip: "상태 표시 팝업에는 추가 계정을 최대 2개까지만 표시할 수 있습니다. 먼저 하나를 해제하세요",
    unknown: "알 수 없음",
    never: "없음",
    resetUnknown: "재설정 시간 알 수 없음"
  },
  it: {
    panelTitle: "Riepilogo quote di Codex Accounts Manager",
    brandSub: "Dashboard principale per cambio account e monitoraggio quote",
    refreshPage: "Aggiorna pagina",
    addAccount: "Aggiungi account",
    importCurrent: "Importa account corrente",
    refreshAll: "Aggiorna quote",
    dashboardTitle: "Codex Accounts Manager · Dashboard quote",
    dashboardSub: "Dashboard principale per monitoraggio, gestione e screenshot",
    empty: "Nessun account salvato",
    noActiveAccountTitle: "Nessun account attivo",
    noActiveAccountSub: "Esistono account salvati, ma nessuno è attualmente contrassegnato come attivo.",
    current: "Corrente",
    hourlyLabel: "5 h",
    weeklyLabel: "Settimanale",
    reviewLabel: "Review",
    userId: "ID utente",
    lastRefresh: "Ultimo aggiornamento",
    accountId: "ID account",
    organization: "Organizzazione",
    savedAccounts: "Account salvati",
    savedAccountsSub: "Gestisci qui gli account salvati, inclusi cambio, aggiornamento, dettagli e rimozione.",
    teamName: "Team",
    login: "Accesso",
    switchBtn: "Cambia",
    refreshBtn: "Aggiorna",
    detailsBtn: "Dettagli",
    removeBtn: "Rimuovi",
    settingsTitle: "Impostazioni",
    codexAppRestartTitle: "Politica di riavvio Codex App",
    codexAppRestartSub:
      "Controlla come l'estensione gestisce Codex App quando è già in esecuzione durante il cambio account.",
    restartModeAuto: "Riavvia automaticamente",
    restartModeAutoDesc: "Se Codex App è già in esecuzione, riavviala subito dopo il cambio account.",
    restartModeManual: "Chiedi ogni volta",
    restartModeManualDesc: "Mantieni la decisione finale nelle tue mani e conferma ogni riavvio manualmente.",
    restartModeNote:
      "L'estensione riavvia Codex App solo quando è già in esecuzione. Non avvia l'app desktop da uno stato fermo.",
    autoRefreshTitle: "Aggiornamento automatico",
    autoRefreshSub: "Aggiorna periodicamente le quote degli account salvati.",
    autoRefreshOn: "Attiva aggiornamento automatico",
    autoRefreshOnDesc: "Aggiorna le quote di tutti gli account salvati a intervalli fissi.",
    autoRefreshOff: "Disattivato",
    autoRefreshOffDesc: "Disattiva l'aggiornamento pianificato e lascia solo quello manuale.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Aggiorna le quote di tutti gli account salvati ogni {value} minuti.",
    autoSwitchTitle: "Cambio automatico account",
    autoSwitchSub: "Quando la quota dell'account attivo diventa bassa, passa automaticamente a un altro account salvato.",
    autoSwitchOn: "Attiva cambio automatico",
    autoSwitchOnDesc:
      "Dopo l'aggiornamento prova a passare a un altro account disponibile quando l'account attivo raggiunge la soglia.",
    autoSwitchOff: "Disattivato",
    autoSwitchOffDesc: "Mantieni l'account attuale finché non cambi manualmente.",
    autoSwitchThresholdSuffix: "soglia di cambio",
    autoSwitchThresholdDescTemplate: "Prova a cambiare quando la quota residua {label} è pari o inferiore a {value}%.",
    autoSwitchAnyNote: "Qualsiasi soglia raggiunta avvia un tentativo di cambio.",
    autoSwitchToastSwitched: "La quota attiva ha raggiunto la soglia di cambio automatico. Passato a {account}.",
    appPathTitle: "Percorso Codex App",
    appPathSub:
      "Opzionale. Imposta un percorso personalizzato per Codex App oppure lascialo vuoto per il rilevamento automatico.",
    appPathEmpty: "Nessun percorso di avvio rilevato. Selezionalo manualmente.",
    pickPath: "Scegli percorso",
    clearPath: "Percorso rilevato automaticamente",
    dashboardSettingsTitle: "Vista dashboard",
    dashboardSettingsSub: "Controlla quali informazioni mostra la dashboard delle quote.",
    showReviewOn: "Mostra quota Code Review",
    showReviewOnDesc: "Mostra la quota Code Review nella dashboard e nelle schede account.",
    showReviewOff: "Nascondi quota Code Review",
    showReviewOffDesc: "Semplifica la dashboard mostrando solo le quote da 5 ore e settimanali.",
    warningTitle: "Avviso quota",
    warningSub: "Mostra un avviso quando la quota residua di 5 ore o settimanale dell'account attivo scende sotto la soglia.",
    warningOn: "Attiva avviso",
    warningOnDesc: "Mostra notifiche dopo l'aggiornamento se la quota residua di 5 ore o quella settimanale scende sotto la soglia.",
    warningOff: "Disattiva avviso",
    warningOffDesc: "Non mostrare notifiche relative alla soglia della quota.",
    warningValueDescTemplate: "Avvisa quando la quota disponibile scende sotto il {value}%.",
    colorThresholdTitle: "Soglie colore",
    colorThresholdSub: "Controlla quando le quote appaiono verdi, gialle o rosse.",
    colorThresholdGreenTitle: "Il verde inizia da",
    colorThresholdYellowTitle: "Il giallo inizia da",
    colorThresholdGreenDescTemplate: "Mostra verde quando la quota disponibile è almeno del {value}%.",
    colorThresholdYellowDescTemplate:
      "Mostra giallo quando la quota disponibile è almeno del {value}% ed è sotto la soglia verde.",
    colorThresholdRedNoteTemplate: "Mostra rosso quando la quota disponibile scende sotto il {value}%.",
    debugTitle: "Log di debug rete",
    debugSub: "Controlla se i riepiloghi delle richieste vengono scritti nel pannello di output.",
    debugOn: "Attiva log di debug",
    debugOnDesc: "Registra risultati ripuliti per aiutare a diagnosticare problemi API.",
    debugOff: "Disattiva log di debug",
    debugOffDesc: "Disattivato per impostazione predefinita per evitare rumore inutile.",
    debugNote:
      "I log vengono scritti nel canale `Codex Accounts Network` con troncamento e mascheramento dei dati sensibili.",
    languageTitle: "Lingua",
    languageSub: "Sostituisce la lingua del dashboard e dei messaggi solo per questa estensione.",
    languageAuto: "Automatico (segui VS Code)",
    languageZh: "Cinese semplificato",
    languageEn: "English",
    languageNote:
      "Le modifiche si applicano subito solo a questa estensione e non influenzano il resto dell'interfaccia di VS Code.",
    statusShort: "Stato",
    statusToggleTip: "Controlla se questo account appare nel popup inferiore della barra di stato",
    statusToggleTipChecked:
      "Questo account è già mostrato nel popup inferiore della barra di stato. Clicca per rimuoverlo",
    statusLimitTip: "Il popup della barra di stato può mostrare al massimo 2 account aggiuntivi. Rimuovine prima uno",
    unknown: "sconosciuto",
    never: "mai",
    resetUnknown: "reset sconosciuto"
  },
  tr: {
    panelTitle: "Codex Accounts Manager kota özeti",
    brandSub: "Çoklu hesap geçişi ve kota izleme için ana pano",
    refreshPage: "Sayfayı yenile",
    addAccount: "Hesap ekle",
    importCurrent: "Geçerli hesabı içe aktar",
    refreshAll: "Kotaları yenile",
    dashboardTitle: "Codex Accounts Manager · Kota panosu",
    dashboardSub: "İzleme, yönetim ve ekran görüntüsü için ana pano",
    empty: "Henüz kayıtlı hesap yok",
    noActiveAccountTitle: "Etkin hesap yok",
    noActiveAccountSub: "Kayıtlı hesaplar var ancak şu anda hiçbiri etkin olarak işaretlenmemiş.",
    current: "Geçerli",
    hourlyLabel: "5 sa",
    weeklyLabel: "Haftalık",
    reviewLabel: "İnceleme",
    userId: "Kullanıcı ID",
    lastRefresh: "Son yenileme",
    accountId: "Hesap ID",
    organization: "Kuruluş",
    savedAccounts: "Kayıtlı hesaplar",
    savedAccountsSub: "Kayıtlı hesapları burada yönetin; geçiş, yenileme, ayrıntılar ve kaldırma işlemlerini yapın.",
    teamName: "Ekip",
    login: "Giriş",
    switchBtn: "Geçiş yap",
    refreshBtn: "Yenile",
    detailsBtn: "Detaylar",
    removeBtn: "Kaldır",
    settingsTitle: "Ayarlar",
    codexAppRestartTitle: "Codex App yeniden başlatma ilkesi",
    codexAppRestartSub:
      "Hesap değiştirirken eklentinin halihazırda çalışan Codex App ile nasıl ilgileneceğini kontrol eder.",
    restartModeAuto: "Otomatik yeniden başlat",
    restartModeAutoDesc: "Codex App zaten çalışıyorsa hesap değişiminden hemen sonra yeniden başlatır.",
    restartModeManual: "Her seferinde sor",
    restartModeManualDesc: "Son kararı sende bırakır ve her yeniden başlatmayı elle onaylatır.",
    restartModeNote:
      "Eklenti Codex App'i yalnızca zaten çalışıyorsa yeniden başlatır. Durdurulmuş durumdan masaüstü uygulamasını açmaz.",
    autoRefreshTitle: "Otomatik yenileme",
    autoRefreshSub: "Kayıtlı hesapların kotalarını düzenli aralıklarla yeniler.",
    autoRefreshOn: "Otomatik yenilemeyi aç",
    autoRefreshOnDesc: "Tüm kayıtlı hesapların kotalarını sabit aralıklarla yeniler.",
    autoRefreshOff: "Kapalı",
    autoRefreshOffDesc: "Zamanlanmış yenilemeyi kapatır ve yalnızca manuel yenileme bırakır.",
    autoRefreshValueTemplate: "{value} dk",
    autoRefreshValueDescTemplate: "Tüm kayıtlı hesapların kotalarını her {value} dakikada bir yeniler.",
    autoSwitchTitle: "Otomatik hesap geçişi",
    autoSwitchSub: "Etkin hesabın kotası düştüğünde başka bir kayıtlı hesaba otomatik olarak geç.",
    autoSwitchOn: "Otomatik geçişi aç",
    autoSwitchOnDesc: "Yenilemeden sonra etkin hesap sınırınıza ulaştığında başka bir uygun hesaba geçmeyi dener.",
    autoSwitchOff: "Kapalı",
    autoSwitchOffDesc: "Siz manuel olarak geçene kadar mevcut hesabı korur.",
    autoSwitchThresholdSuffix: "geçiş eşiği",
    autoSwitchThresholdDescTemplate: "{label} kalan kotası {value}% veya altına düştüğünde geçiş dene.",
    autoSwitchAnyNote: "Herhangi bir eşik tetiklenirse geçiş denemesi başlatılır.",
    autoSwitchToastSwitched: "Etkin kota otomatik geçiş eşiğine ulaştı. {account} hesabına geçildi.",
    appPathTitle: "Codex App yolu",
    appPathSub: "İsteğe bağlıdır. Codex App için özel bir yol belirtin veya otomatik algılama için boş bırakın.",
    appPathEmpty: "Başlatma yolu algılanmadı. Lütfen manuel olarak seçin.",
    pickPath: "Yol seç",
    clearPath: "Otomatik algılanan yol",
    dashboardSettingsTitle: "Pano görünümü",
    dashboardSettingsSub: "Kota panosunda hangi bilgilerin gösterileceğini kontrol eder.",
    showReviewOn: "Code Review kotasını göster",
    showReviewOnDesc: "Code Review kotasını panoda ve hesap kartlarında gösterir.",
    showReviewOff: "Code Review kotasını gizle",
    showReviewOffDesc: "Panoyu sadeleştirir ve yalnızca 5 saatlik ile haftalık kotaları gösterir.",
    warningTitle: "Kota uyarısı",
    warningSub: "Etkin hesabın 5 saatlik veya haftalık kalan kotası eşik değerin altına düştüğünde uyarı gösterir.",
    warningOn: "Uyarıyı aç",
    warningOnDesc: "Yenilemeden sonra 5 saatlik veya haftalık kalan kotadan biri eşik değerin altındaysa bildirim gösterir.",
    warningOff: "Uyarıyı kapat",
    warningOffDesc: "Kota eşik bildirimlerini göstermez.",
    warningValueDescTemplate: "Kullanılabilir kota {value}% altına düştüğünde uyar.",
    colorThresholdTitle: "Renk eşikleri",
    colorThresholdSub: "Kotaların ne zaman yeşil, sarı veya kırmızı görüneceğini kontrol eder.",
    colorThresholdGreenTitle: "Yeşil başlangıcı",
    colorThresholdYellowTitle: "Sarı başlangıcı",
    colorThresholdGreenDescTemplate: "Kullanılabilir kota en az {value}% olduğunda yeşil gösterir.",
    colorThresholdYellowDescTemplate:
      "Kullanılabilir kota en az {value}% olduğunda ve yeşil eşiğin altında kaldığında sarı gösterir.",
    colorThresholdRedNoteTemplate: "Kullanılabilir kota {value}% altına düştüğünde kırmızı gösterir.",
    debugTitle: "Ağ hata ayıklama günlükleri",
    debugSub: "İstek özetlerinin çıktı paneline yazılıp yazılmayacağını kontrol eder.",
    debugOn: "Hata ayıklama günlüklerini aç",
    debugOnDesc: "API sorunlarını teşhis etmeye yardımcı olmak için temizlenmiş istek sonuçlarını kaydeder.",
    debugOff: "Hata ayıklama günlüklerini kapat",
    debugOffDesc: "Gereksiz hata ayıklama gürültüsünü önlemek için varsayılan olarak kapalıdır.",
    debugNote: "Günlükler `Codex Accounts Network` çıktı kanalına yazılır; hassas veriler kısaltılır ve maskelenir.",
    languageTitle: "Dil",
    languageSub: "Yalnızca bu eklenti için pano ve bildirim dilini geçersiz kılar.",
    languageAuto: "Otomatik (VS Code'u takip et)",
    languageZh: "Basitleştirilmiş Çince",
    languageEn: "English",
    languageNote: "Değişiklikler hemen yalnızca bu eklentiye uygulanır ve VS Code arayüzünün geri kalanını etkilemez.",
    statusShort: "Durum",
    statusToggleTip: "Bu hesabın alttaki durum açılır penceresinde görünüp görünmeyeceğini kontrol eder",
    statusToggleTipChecked: "Bu hesap zaten alttaki durum açılır penceresinde gösteriliyor. Kaldırmak için tıklayın",
    statusLimitTip: "Durum açılır penceresinde en fazla 2 ek hesap gösterilebilir. Önce birini kaldırın",
    unknown: "bilinmiyor",
    never: "asla",
    resetUnknown: "sıfırlama bilinmiyor"
  },
  pl: {
    panelTitle: "Podsumowanie limitów Codex Accounts Manager",
    brandSub: "Główny panel do przełączania kont i monitorowania limitów",
    refreshPage: "Odśwież stronę",
    addAccount: "Dodaj konto",
    importCurrent: "Importuj bieżące konto",
    refreshAll: "Odśwież limity",
    dashboardTitle: "Codex Accounts Manager · Panel limitów",
    dashboardSub: "Główny panel do monitorowania, zarządzania i zrzutów ekranu",
    empty: "Brak zapisanych kont",
    noActiveAccountTitle: "Brak aktywnego konta",
    noActiveAccountSub: "Istnieją zapisane konta, ale żadne nie jest obecnie oznaczone jako aktywne.",
    current: "Bieżące",
    hourlyLabel: "5 godz.",
    weeklyLabel: "Tygodniowo",
    reviewLabel: "Przegląd",
    userId: "ID użytkownika",
    lastRefresh: "Ostatnie odświeżenie",
    accountId: "ID konta",
    organization: "Organizacja",
    savedAccounts: "Zapisane konta",
    savedAccountsSub: "Tutaj zarządzisz zapisanymi kontami: przełączaniem, odświeżaniem, szczegółami i usuwaniem.",
    teamName: "Zespół",
    login: "Logowanie",
    switchBtn: "Przełącz",
    refreshBtn: "Odśwież",
    detailsBtn: "Szczegóły",
    removeBtn: "Usuń",
    settingsTitle: "Ustawienia",
    codexAppRestartTitle: "Zasady restartu Codex App",
    codexAppRestartSub:
      "Określa, jak rozszerzenie obsługuje już uruchomioną aplikację Codex App podczas przełączania kont.",
    restartModeAuto: "Uruchom ponownie automatycznie",
    restartModeAutoDesc:
      "Jeśli Codex App jest już uruchomiona, zostanie natychmiast ponownie uruchomiona po zmianie konta.",
    restartModeManual: "Pytaj za każdym razem",
    restartModeManualDesc: "Ostateczna decyzja pozostaje po twojej stronie, a każdy restart wymaga potwierdzenia.",
    restartModeNote:
      "Rozszerzenie restartuje Codex App tylko wtedy, gdy aplikacja już działa. Nie uruchomi aplikacji desktopowej z zatrzymanego stanu.",
    autoRefreshTitle: "Automatyczne odświeżanie",
    autoRefreshSub: "Okresowo odświeża limity zapisanych kont.",
    autoRefreshOn: "Włącz automatyczne odświeżanie",
    autoRefreshOnDesc: "Odświeża limity wszystkich zapisanych kont w stałych odstępach czasu.",
    autoRefreshOff: "Wyłączone",
    autoRefreshOffDesc: "Wyłącza odświeżanie cykliczne i pozostawia tylko ręczne odświeżanie.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Odświeża limity wszystkich zapisanych kont co {value} minut.",
    autoSwitchTitle: "Automatyczne przełączanie konta",
    autoSwitchSub: "Gdy limit aktywnego konta jest niski, automatycznie przełącz na inne zapisane konto.",
    autoSwitchOn: "Włącz automatyczne przełączanie",
    autoSwitchOnDesc:
      "Po odświeżeniu próbuje przełączyć na inne dostępne konto, gdy aktywne konto osiągnie ustawiony próg.",
    autoSwitchOff: "Wyłączone",
    autoSwitchOffDesc: "Pozostawia bieżące konto do czasu ręcznego przełączenia.",
    autoSwitchThresholdSuffix: "próg przełączenia",
    autoSwitchThresholdDescTemplate: "Spróbuj przełączyć, gdy pozostały limit {label} wynosi {value}% lub mniej.",
    autoSwitchAnyNote: "Osiągnięcie dowolnego progu uruchamia próbę przełączenia.",
    autoSwitchToastSwitched:
      "Limit aktywnego konta osiągnął próg automatycznego przełączenia. Przełączono na {account}.",
    appPathTitle: "Ścieżka Codex App",
    appPathSub:
      "Opcjonalne. Ustaw własną ścieżkę do Codex App albo pozostaw puste, aby użyć automatycznego wykrywania.",
    appPathEmpty: "Nie wykryto ścieżki uruchamiania. Wybierz ją ręcznie.",
    pickPath: "Wybierz ścieżkę",
    clearPath: "Ścieżka wykrywana automatycznie",
    dashboardSettingsTitle: "Widok panelu",
    dashboardSettingsSub: "Kontroluje, jakie informacje pokazuje panel limitów.",
    showReviewOn: "Pokaż limit Code Review",
    showReviewOnDesc: "Pokazuje limit Code Review na panelu i kartach kont.",
    showReviewOff: "Ukryj limit Code Review",
    showReviewOffDesc: "Upraszcza panel, pokazując tylko limity 5-godzinne i tygodniowe.",
    warningTitle: "Ostrzeżenie o limicie",
    warningSub: "Pokazuje ostrzeżenie, gdy pozostały limit 5-godzinny lub tygodniowy aktywnego konta spadnie poniżej progu.",
    warningOn: "Włącz ostrzeżenie",
    warningOnDesc: "Pokazuje powiadomienia po odświeżeniu, jeśli pozostały limit 5-godzinny lub tygodniowy jest poniżej progu.",
    warningOff: "Wyłącz ostrzeżenie",
    warningOffDesc: "Nie pokazuj powiadomień o progach limitu.",
    warningValueDescTemplate: "Ostrzegaj, gdy dostępny limit spadnie poniżej {value}%.",
    colorThresholdTitle: "Progi kolorów",
    colorThresholdSub: "Kontroluje, kiedy limity są pokazywane na zielono, żółto lub czerwono.",
    colorThresholdGreenTitle: "Zielony zaczyna się od",
    colorThresholdYellowTitle: "Żółty zaczyna się od",
    colorThresholdGreenDescTemplate: "Pokazuje zielony, gdy dostępny limit wynosi co najmniej {value}%.",
    colorThresholdYellowDescTemplate:
      "Pokazuje żółty, gdy dostępny limit wynosi co najmniej {value}% i jest poniżej progu zielonego.",
    colorThresholdRedNoteTemplate: "Pokazuje czerwony, gdy dostępny limit spada poniżej {value}%.",
    debugTitle: "Logi debugowania sieci",
    debugSub: "Kontroluje, czy podsumowania żądań są zapisywane w panelu wyjścia.",
    debugOn: "Włącz logi debugowania",
    debugOnDesc: "Zapisuje oczyszczone wyniki żądań, aby ułatwić diagnozowanie problemów z API.",
    debugOff: "Wyłącz logi debugowania",
    debugOffDesc: "Domyślnie wyłączone, aby uniknąć zbędnego szumu debugowania.",
    debugNote: "Logi są zapisywane w kanale `Codex Accounts Network`, a wrażliwe dane są skracane i maskowane.",
    languageTitle: "Język",
    languageSub: "Nadpisuje język panelu i komunikatów tylko dla tego rozszerzenia.",
    languageAuto: "Automatycznie (zgodnie z VS Code)",
    languageZh: "Chiński uproszczony",
    languageEn: "English",
    languageNote:
      "Zmiany są stosowane natychmiast tylko do tego rozszerzenia i nie wpływają na resztę interfejsu VS Code.",
    statusShort: "Status",
    statusToggleTip: "Kontroluje, czy to konto pojawia się w dolnym wyskakującym oknie paska stanu",
    statusToggleTipChecked:
      "To konto jest już pokazywane w dolnym wyskakującym oknie paska stanu. Kliknij, aby je usunąć",
    statusLimitTip: "W wyskakującym oknie paska stanu można pokazać maksymalnie 2 dodatkowe konta. Najpierw usuń jedno",
    unknown: "nieznane",
    never: "nigdy",
    resetUnknown: "reset nieznany"
  },
  cs: {
    panelTitle: "Přehled kvót Codex Accounts Manager",
    brandSub: "Hlavní panel pro přepínání účtů a sledování kvót",
    refreshPage: "Obnovit stránku",
    addAccount: "Přidat účet",
    importCurrent: "Importovat aktuální účet",
    refreshAll: "Obnovit kvóty",
    dashboardTitle: "Codex Accounts Manager · Panel kvót",
    dashboardSub: "Hlavní panel pro monitoring, správu a snímky obrazovky",
    empty: "Zatím nejsou uloženy žádné účty",
    noActiveAccountTitle: "Žádný aktivní účet",
    noActiveAccountSub: "Uložené účty existují, ale žádný z nich není aktuálně označen jako aktivní.",
    current: "Aktuální",
    hourlyLabel: "5 h",
    weeklyLabel: "Týdně",
    reviewLabel: "Revize",
    userId: "ID uživatele",
    lastRefresh: "Poslední obnovení",
    accountId: "ID účtu",
    organization: "Organizace",
    savedAccounts: "Uložené účty",
    savedAccountsSub: "Zde můžete spravovat uložené účty včetně přepínání, obnovení, detailů a odstranění.",
    teamName: "Tým",
    login: "Přihlášení",
    switchBtn: "Přepnout",
    refreshBtn: "Obnovit",
    detailsBtn: "Detaily",
    removeBtn: "Odstranit",
    settingsTitle: "Nastavení",
    codexAppRestartTitle: "Zásady restartu Codex App",
    codexAppRestartSub: "Určuje, jak rozšíření zachází s již spuštěnou aplikací Codex App při přepínání účtů.",
    restartModeAuto: "Restartovat automaticky",
    restartModeAutoDesc: "Pokud je Codex App již spuštěný, po přepnutí účtu se ihned restartuje.",
    restartModeManual: "Ptát se pokaždé",
    restartModeManualDesc: "Konečné rozhodnutí zůstává na vás a každý restart je třeba ručně potvrdit.",
    restartModeNote:
      "Rozšíření restartuje Codex App pouze tehdy, když už běží. Nespustí desktopovou aplikaci ze zastaveného stavu.",
    autoRefreshTitle: "Automatické obnovování",
    autoRefreshSub: "Pravidelně obnovuje kvóty uložených účtů.",
    autoRefreshOn: "Zapnout automatické obnovování",
    autoRefreshOnDesc: "Obnovuje kvóty všech uložených účtů v pevných intervalech.",
    autoRefreshOff: "Vypnuto",
    autoRefreshOffDesc: "Vypne plánované obnovování a ponechá jen ruční obnovu.",
    autoRefreshValueTemplate: "{value} min",
    autoRefreshValueDescTemplate: "Obnovuje kvóty všech uložených účtů každých {value} minut.",
    autoSwitchTitle: "Automatické přepínání účtu",
    autoSwitchSub: "Když kvóta aktivního účtu klesne, automaticky se přepne na jiný uložený účet.",
    autoSwitchOn: "Zapnout automatické přepínání",
    autoSwitchOnDesc: "Po obnovení se pokusí přepnout na jiný dostupný účet, když aktivní účet dosáhne vašeho limitu.",
    autoSwitchOff: "Vypnuto",
    autoSwitchOffDesc: "Ponechá aktuální účet, dokud ho nepřepnete ručně.",
    autoSwitchThresholdSuffix: "práh přepnutí",
    autoSwitchThresholdDescTemplate: "Zkusit přepnout, když zbývající kvóta {label} klesne na {value}% nebo méně.",
    autoSwitchAnyNote: "Jakmile je dosažen kterýkoli práh, spustí se pokus o přepnutí.",
    autoSwitchToastSwitched:
      "Kvóta aktivního účtu dosáhla prahu automatického přepnutí. Přepnuto na {account}.",
    appPathTitle: "Cesta k Codex App",
    appPathSub: "Volitelné. Nastavte vlastní cestu k Codex App, nebo ponechte prázdné pro automatickou detekci.",
    appPathEmpty: "Nebyla zjištěna spouštěcí cesta. Vyberte ji ručně.",
    pickPath: "Vybrat cestu",
    clearPath: "Automaticky zjištěná cesta",
    dashboardSettingsTitle: "Zobrazení panelu",
    dashboardSettingsSub: "Určuje, jaké informace se zobrazují na panelu kvót.",
    showReviewOn: "Zobrazit kvótu Code Review",
    showReviewOnDesc: "Zobrazuje kvótu Code Review na panelu a v kartách účtů.",
    showReviewOff: "Skrýt kvótu Code Review",
    showReviewOffDesc: "Zjednoduší panel a zobrazí jen 5hodinové a týdenní kvóty.",
    warningTitle: "Upozornění na kvótu",
    warningSub: "Zobrazí upozornění, když zbývající 5hodinová nebo týdenní kvóta aktivního účtu klesne pod práh.",
    warningOn: "Zapnout upozornění",
    warningOnDesc: "Po obnovení zobrazí oznámení, pokud zbývající 5hodinová nebo týdenní kvóta klesne pod práh.",
    warningOff: "Vypnout upozornění",
    warningOffDesc: "Nezobrazovat oznámení o prahu kvóty.",
    warningValueDescTemplate: "Upozornit, když dostupná kvóta klesne pod {value}%.",
    colorThresholdTitle: "Barevné prahy",
    colorThresholdSub: "Určuje, kdy se kvóty zobrazují zeleně, žlutě nebo červeně.",
    colorThresholdGreenTitle: "Zelená začíná na",
    colorThresholdYellowTitle: "Žlutá začíná na",
    colorThresholdGreenDescTemplate: "Zobrazí zelenou, když je dostupná kvóta alespoň {value}%.",
    colorThresholdYellowDescTemplate:
      "Zobrazí žlutou, když je dostupná kvóta alespoň {value}% a zároveň pod zeleným prahem.",
    colorThresholdRedNoteTemplate: "Zobrazí červenou, když dostupná kvóta klesne pod {value}%.",
    debugTitle: "Síťové debug logy",
    debugSub: "Určuje, zda se shrnutí požadavků zapisují do výstupního panelu.",
    debugOn: "Zapnout debug logy",
    debugOnDesc: "Zaznamenává očištěné výsledky požadavků pro snadnější diagnostiku problémů API.",
    debugOff: "Vypnout debug logy",
    debugOffDesc: "Ve výchozím stavu vypnuto, aby se předešlo zbytečnému šumu.",
    debugNote: "Logy se zapisují do kanálu `Codex Accounts Network`, přičemž citlivá data jsou zkracována a maskována.",
    languageTitle: "Jazyk",
    languageSub: "Přepíše jazyk panelu a oznámení pouze pro toto rozšíření.",
    languageAuto: "Automaticky (sledovat VS Code)",
    languageZh: "Zjednodušená čínština",
    languageEn: "English",
    languageNote: "Změny se okamžitě projeví jen v tomto rozšíření a neovlivní zbytek rozhraní VS Code.",
    statusShort: "Stav",
    statusToggleTip: "Určuje, zda se tento účet zobrazí ve spodním vyskakovacím okně stavového řádku",
    statusToggleTipChecked:
      "Tento účet je už zobrazen ve spodním vyskakovacím okně stavového řádku. Kliknutím ho odeberete",
    statusLimitTip: "Ve vyskakovacím okně stavového řádku lze zobrazit maximálně 2 další účty. Nejprve jeden odeberte",
    unknown: "neznámé",
    never: "nikdy",
    resetUnknown: "čas resetu neznámý"
  },
  ar: {
    panelTitle: "ملخص حصص Codex Accounts Manager",
    brandSub: "لوحة رئيسية للتبديل بين الحسابات ومراقبة الحصص",
    refreshPage: "تحديث الصفحة",
    addAccount: "إضافة حساب",
    importCurrent: "استيراد الحساب الحالي",
    refreshAll: "تحديث الحصص",
    dashboardTitle: "Codex Accounts Manager · لوحة الحصص",
    dashboardSub: "اللوحة الرئيسية للمراقبة والإدارة ولقطات الشاشة",
    empty: "لا توجد حسابات محفوظة بعد",
    noActiveAccountTitle: "لا يوجد حساب نشط",
    noActiveAccountSub: "توجد حسابات محفوظة، لكن لا يوجد أي حساب مميز حاليًا كحساب نشط.",
    current: "الحالي",
    hourlyLabel: "5 س",
    weeklyLabel: "أسبوعي",
    reviewLabel: "مراجعة",
    userId: "معرّف المستخدم",
    lastRefresh: "آخر تحديث",
    accountId: "معرّف الحساب",
    organization: "المؤسسة",
    savedAccounts: "الحسابات المحفوظة",
    savedAccountsSub: "أدِر الحسابات المحفوظة هنا، بما في ذلك التبديل والتحديث والتفاصيل والإزالة.",
    teamName: "الفريق",
    login: "تسجيل الدخول",
    switchBtn: "تبديل",
    refreshBtn: "تحديث",
    detailsBtn: "تفاصيل",
    removeBtn: "إزالة",
    settingsTitle: "الإعدادات",
    codexAppRestartTitle: "سياسة إعادة تشغيل Codex App",
    codexAppRestartSub: "تتحكم في كيفية تعامل الإضافة مع Codex App عندما يكون قيد التشغيل أثناء تبديل الحسابات.",
    restartModeAuto: "إعادة التشغيل تلقائيًا",
    restartModeAutoDesc: "إذا كان Codex App يعمل بالفعل، فأعد تشغيله مباشرة بعد تبديل الحساب.",
    restartModeManual: "السؤال في كل مرة",
    restartModeManualDesc: "يُبقي القرار النهائي بيدك ويطلب تأكيدًا يدويًا لكل إعادة تشغيل.",
    restartModeNote:
      "تعيد الإضافة تشغيل Codex App فقط عندما يكون قيد التشغيل بالفعل. ولن تشغّل تطبيق سطح المكتب من حالة التوقف.",
    autoRefreshTitle: "التحديث التلقائي",
    autoRefreshSub: "تحدّث حصص الحسابات المحفوظة بشكل دوري.",
    autoRefreshOn: "تفعيل التحديث التلقائي",
    autoRefreshOnDesc: "تحدّث حصص جميع الحسابات المحفوظة على فاصل زمني ثابت.",
    autoRefreshOff: "إيقاف",
    autoRefreshOffDesc: "تعطّل التحديث المجدول وتترك التحديث اليدوي فقط.",
    autoRefreshValueTemplate: "{value} دقيقة",
    autoRefreshValueDescTemplate: "تحدّث حصص جميع الحسابات المحفوظة كل {value} دقيقة.",
    autoSwitchTitle: "التبديل التلقائي للحساب",
    autoSwitchSub: "عندما تنخفض حصة الحساب النشط، بدّل تلقائيًا إلى حساب محفوظ آخر.",
    autoSwitchOn: "تفعيل التبديل التلقائي",
    autoSwitchOnDesc: "بعد التحديث، يحاول الانتقال إلى حساب آخر متاح عندما يصل الحساب النشط إلى الحد الذي حددته.",
    autoSwitchOff: "إيقاف",
    autoSwitchOffDesc: "أبقِ الحساب الحالي حتى تبدّله يدويًا.",
    autoSwitchThresholdSuffix: "حد التبديل",
    autoSwitchThresholdDescTemplate: "حاول التبديل عندما تصبح الحصة المتبقية لـ {label} عند {value}% أو أقل.",
    autoSwitchAnyNote: "الوصول إلى أي حد سيؤدي إلى محاولة تبديل.",
    autoSwitchToastSwitched: "وصلت حصة الحساب النشط إلى حد التبديل التلقائي. تم التبديل إلى {account}.",
    appPathTitle: "مسار Codex App",
    appPathSub: "اختياري. حدّد مسارًا مخصصًا لـ Codex App أو اتركه فارغًا لاستخدام الاكتشاف التلقائي.",
    appPathEmpty: "لم يتم اكتشاف مسار التشغيل. يُرجى اختياره يدويًا.",
    pickPath: "اختيار المسار",
    clearPath: "المسار المكتشف تلقائيًا",
    dashboardSettingsTitle: "عرض اللوحة",
    dashboardSettingsSub: "يتحكم في المعلومات التي تعرضها لوحة الحصص.",
    showReviewOn: "إظهار حصة Code Review",
    showReviewOnDesc: "يعرض حصة Code Review في اللوحة وبطاقات الحسابات.",
    showReviewOff: "إخفاء حصة Code Review",
    showReviewOffDesc: "يبسّط اللوحة ويعرض فقط حصص 5 ساعات والحصة الأسبوعية.",
    warningTitle: "تنبيه الحصة",
    warningSub: "يعرض تنبيهًا عندما تنخفض الحصة المتبقية لمدة 5 ساعات أو الحصة الأسبوعية للحساب النشط تحت الحد المحدد.",
    warningOn: "تفعيل التنبيه",
    warningOnDesc: "يعرض إشعارات بعد التحديث إذا كانت الحصة المتبقية لمدة 5 ساعات أو الحصة الأسبوعية أقل من الحد.",
    warningOff: "إيقاف التنبيه",
    warningOffDesc: "لا تعرض إشعارات حد الحصة.",
    warningValueDescTemplate: "نبّه عندما تنخفض الحصة المتاحة تحت {value}%.",
    colorThresholdTitle: "حدود الألوان",
    colorThresholdSub: "يتحكم في وقت ظهور الحصص باللون الأخضر أو الأصفر أو الأحمر.",
    colorThresholdGreenTitle: "يبدأ الأخضر عند",
    colorThresholdYellowTitle: "يبدأ الأصفر عند",
    colorThresholdGreenDescTemplate: "اعرض اللون الأخضر عندما تكون الحصة المتاحة {value}% أو أكثر.",
    colorThresholdYellowDescTemplate:
      "اعرض اللون الأصفر عندما تكون الحصة المتاحة {value}% أو أكثر وأقل من حد اللون الأخضر.",
    colorThresholdRedNoteTemplate: "اعرض اللون الأحمر عندما تنخفض الحصة المتاحة تحت {value}%.",
    debugTitle: "سجلات تصحيح الشبكة",
    debugSub: "يتحكم فيما إذا كانت ملخصات الطلبات تُكتب في لوحة الإخراج.",
    debugOn: "تفعيل سجلات التصحيح",
    debugOnDesc: "يسجل نتائج الطلبات بعد إزالة البيانات الحساسة للمساعدة في تشخيص مشاكل API.",
    debugOff: "إيقاف سجلات التصحيح",
    debugOffDesc: "متوقفة افتراضيًا لتجنب الضوضاء غير الضرورية.",
    debugNote: "تُكتب السجلات في قناة الإخراج `Codex Accounts Network` مع اقتطاع البيانات الحساسة وإخفائها.",
    languageTitle: "اللغة",
    languageSub: "يتجاوز لغة اللوحة والتنبيهات لهذا الامتداد فقط.",
    languageAuto: "تلقائي (اتباع VS Code)",
    languageZh: "الصينية المبسطة",
    languageEn: "English",
    languageNote: "تُطبق التغييرات فورًا على هذا الامتداد فقط ولا تؤثر في بقية واجهة VS Code.",
    statusShort: "الحالة",
    statusToggleTip: "يتحكم فيما إذا كان هذا الحساب يظهر في النافذة المنبثقة السفلية لشريط الحالة",
    statusToggleTipChecked: "هذا الحساب ظاهر بالفعل في النافذة المنبثقة السفلية لشريط الحالة. انقر لإزالته",
    statusLimitTip: "يمكن إظهار حسابين إضافيين كحد أقصى في نافذة شريط الحالة المنبثقة. أزل واحدًا أولًا",
    unknown: "غير معروف",
    never: "أبدًا",
    resetUnknown: "وقت إعادة التعيين غير معروف"
  },
  vi: {
    panelTitle: "Tóm tắt hạn mức Codex Accounts Manager",
    brandSub: "Bảng điều khiển chính để chuyển tài khoản và theo dõi hạn mức",
    refreshPage: "Làm mới trang",
    addAccount: "Thêm tài khoản",
    importCurrent: "Nhập tài khoản hiện tại",
    refreshAll: "Làm mới hạn mức",
    dashboardTitle: "Codex Accounts Manager · Bảng hạn mức",
    dashboardSub: "Bảng chính để theo dõi, quản lý và chụp màn hình",
    empty: "Chưa có tài khoản nào được lưu",
    noActiveAccountTitle: "Không có tài khoản đang hoạt động",
    noActiveAccountSub: "Có tài khoản đã lưu nhưng hiện không có tài khoản nào được đánh dấu là đang hoạt động.",
    current: "Hiện tại",
    hourlyLabel: "5 giờ",
    weeklyLabel: "Hàng tuần",
    reviewLabel: "Đánh giá",
    userId: "ID người dùng",
    lastRefresh: "Lần làm mới gần nhất",
    accountId: "ID tài khoản",
    organization: "Tổ chức",
    savedAccounts: "Tài khoản đã lưu",
    savedAccountsSub: "Quản lý các tài khoản đã lưu tại đây, bao gồm chuyển đổi, làm mới, xem chi tiết và xóa.",
    teamName: "Nhóm",
    login: "Đăng nhập",
    switchBtn: "Chuyển",
    refreshBtn: "Làm mới",
    detailsBtn: "Chi tiết",
    removeBtn: "Xóa",
    settingsTitle: "Cài đặt",
    codexAppRestartTitle: "Chính sách khởi động lại Codex App",
    codexAppRestartSub: "Kiểm soát cách tiện ích xử lý Codex App đang chạy khi chuyển tài khoản.",
    restartModeAuto: "Tự động khởi động lại",
    restartModeAutoDesc: "Nếu Codex App đang chạy, hãy khởi động lại ngay sau khi chuyển tài khoản.",
    restartModeManual: "Hỏi mỗi lần",
    restartModeManualDesc:
      "Giữ quyền quyết định cuối cùng trong tay bạn và xác nhận thủ công cho mỗi lần khởi động lại.",
    restartModeNote:
      "Tiện ích chỉ khởi động lại Codex App khi nó đã đang chạy. Nó sẽ không mở ứng dụng desktop từ trạng thái tắt.",
    autoRefreshTitle: "Tự động làm mới",
    autoRefreshSub: "Làm mới hạn mức của các tài khoản đã lưu theo chu kỳ.",
    autoRefreshOn: "Bật tự động làm mới",
    autoRefreshOnDesc: "Làm mới hạn mức của tất cả tài khoản đã lưu theo khoảng thời gian cố định.",
    autoRefreshOff: "Tắt",
    autoRefreshOffDesc: "Tắt làm mới theo lịch và chỉ làm mới thủ công khi cần.",
    autoRefreshValueTemplate: "{value} phút",
    autoRefreshValueDescTemplate: "Làm mới hạn mức của tất cả tài khoản đã lưu mỗi {value} phút.",
    autoSwitchTitle: "Tự động chuyển tài khoản",
    autoSwitchSub: "Khi hạn mức của tài khoản đang hoạt động xuống thấp, tự động chuyển sang tài khoản đã lưu khác.",
    autoSwitchOn: "Bật tự động chuyển",
    autoSwitchOnDesc: "Sau khi làm mới, thử chuyển sang tài khoản khả dụng khác khi tài khoản hiện tại chạm ngưỡng của bạn.",
    autoSwitchOff: "Tắt",
    autoSwitchOffDesc: "Giữ nguyên tài khoản hiện tại cho đến khi bạn tự chuyển thủ công.",
    autoSwitchThresholdSuffix: "ngưỡng chuyển",
    autoSwitchThresholdDescTemplate: "Thử chuyển khi hạn mức còn lại của {label} ở mức {value}% hoặc thấp hơn.",
    autoSwitchAnyNote: "Chạm bất kỳ ngưỡng nào cũng sẽ kích hoạt một lần thử chuyển.",
    autoSwitchToastSwitched: "Hạn mức của tài khoản đang hoạt động đã chạm ngưỡng tự động chuyển. Đã chuyển sang {account}.",
    appPathTitle: "Đường dẫn Codex App",
    appPathSub: "Tùy chọn. Đặt đường dẫn tùy chỉnh cho Codex App hoặc để trống để dùng tính năng tự động phát hiện.",
    appPathEmpty: "Không phát hiện được đường dẫn khởi động. Hãy chọn thủ công.",
    pickPath: "Chọn đường dẫn",
    clearPath: "Đường dẫn tự động phát hiện",
    dashboardSettingsTitle: "Hiển thị bảng",
    dashboardSettingsSub: "Kiểm soát những thông tin nào được hiển thị trên bảng hạn mức.",
    showReviewOn: "Hiển thị hạn mức Code Review",
    showReviewOnDesc: "Hiển thị hạn mức Code Review trên bảng và trong thẻ tài khoản.",
    showReviewOff: "Ẩn hạn mức Code Review",
    showReviewOffDesc: "Giữ bảng gọn hơn chỉ với hạn mức 5 giờ và hàng tuần.",
    warningTitle: "Cảnh báo hạn mức",
    warningSub: "Hiển thị cảnh báo khi hạn mức còn lại 5 giờ hoặc hàng tuần của tài khoản đang hoạt động giảm xuống dưới ngưỡng.",
    warningOn: "Bật cảnh báo",
    warningOnDesc: "Hiển thị thông báo sau khi làm mới nếu hạn mức còn lại 5 giờ hoặc hàng tuần thấp hơn ngưỡng.",
    warningOff: "Tắt cảnh báo",
    warningOffDesc: "Không hiển thị thông báo ngưỡng hạn mức.",
    warningValueDescTemplate: "Cảnh báo khi hạn mức khả dụng giảm dưới {value}%.",
    colorThresholdTitle: "Ngưỡng màu",
    colorThresholdSub: "Kiểm soát khi nào hạn mức hiển thị màu xanh, vàng hoặc đỏ.",
    colorThresholdGreenTitle: "Xanh lá bắt đầu từ",
    colorThresholdYellowTitle: "Vàng bắt đầu từ",
    colorThresholdGreenDescTemplate: "Hiển thị màu xanh khi hạn mức khả dụng ít nhất là {value}%.",
    colorThresholdYellowDescTemplate:
      "Hiển thị màu vàng khi hạn mức khả dụng ít nhất là {value}% và thấp hơn ngưỡng xanh lá.",
    colorThresholdRedNoteTemplate: "Hiển thị màu đỏ khi hạn mức khả dụng giảm dưới {value}%.",
    debugTitle: "Nhật ký gỡ lỗi mạng",
    debugSub: "Kiểm soát việc có ghi tóm tắt yêu cầu vào bảng đầu ra hay không.",
    debugOn: "Bật nhật ký gỡ lỗi",
    debugOnDesc: "Ghi lại kết quả yêu cầu đã được làm sạch để hỗ trợ chẩn đoán sự cố API.",
    debugOff: "Tắt nhật ký gỡ lỗi",
    debugOffDesc: "Mặc định tắt để tránh nhiễu gỡ lỗi không cần thiết.",
    debugNote: "Nhật ký được ghi vào kênh `Codex Accounts Network`, với dữ liệu nhạy cảm được cắt bớt và che đi.",
    languageTitle: "Ngôn ngữ",
    languageSub: "Ghi đè ngôn ngữ bảng điều khiển và thông báo chỉ cho tiện ích này.",
    languageAuto: "Tự động (theo VS Code)",
    languageZh: "Tiếng Trung giản thể",
    languageEn: "English",
    languageNote:
      "Thay đổi được áp dụng ngay cho tiện ích này và không ảnh hưởng đến phần còn lại của giao diện VS Code.",
    statusShort: "Trạng thái",
    statusToggleTip:
      "Kiểm soát việc tài khoản này có xuất hiện trong cửa sổ bật lên của thanh trạng thái phía dưới hay không",
    statusToggleTipChecked:
      "Tài khoản này đã được hiển thị trong cửa sổ bật lên của thanh trạng thái phía dưới. Nhấp để bỏ",
    statusLimitTip:
      "Cửa sổ bật lên của thanh trạng thái chỉ có thể hiển thị tối đa 2 tài khoản bổ sung. Hãy bỏ một tài khoản trước",
    unknown: "không rõ",
    never: "chưa bao giờ",
    resetUnknown: "không rõ thời điểm đặt lại"
  }
}) satisfies Record<DashboardLanguage, DashboardCopy>;
