import { defineLocaleResources } from "../resourceBuilder";

type DetailCopyResource = {
  titlePrefix: string;
  detailsSubtitle: string;
  current: string;
  saved: string;
  showSensitive: string;
  hideSensitive: string;
  currentlyActive: string;
  savedAccount: string;
  teamName: string;
  login: string;
  loginTime: string;
  userId: string;
  status: string;
  hourlyQuota: string;
  weeklyQuota: string;
  reviewQuota: string;
  reset: string;
  usageTitle: string;
  usageHint: string;
  usageSubtitle: string;
  usageLoading: string;
  usageEmpty: string;
  usageError: string;
  rangeLabelTemplate: string;
  metadata: string;
  accountId: string;
  organizationId: string;
  lastQuotaRefresh: string;
  resetUnknown: string;
  never: string;
};

const en: DetailCopyResource = {
  titlePrefix: "Codex",
  detailsSubtitle: "Account details and usage view",
  current: "Current",
  saved: "Saved",
  showSensitive: "Show sensitive info",
  hideSensitive: "Hide sensitive info",
  currentlyActive: "Currently active",
  savedAccount: "Saved account",
  teamName: "Team Name",
  login: "Login",
  loginTime: "Login Time",
  userId: "User ID",
  status: "Status",
  hourlyQuota: "Hourly quota",
  weeklyQuota: "Weekly quota",
  reviewQuota: "Code review quota",
  reset: "Reset",
  usageTitle: "Usage details",
  usageHint: "Usage data is approximate and may be delayed.",
  usageSubtitle: "Personal usage",
  usageLoading: "Loading daily usage...",
  usageEmpty: "No data available for this period",
  usageError: "Failed to load daily usage.",
  rangeLabelTemplate: "Last {days} days",
  metadata: "Metadata",
  accountId: "Account ID",
  organizationId: "Organization ID",
  lastQuotaRefresh: "Last quota refresh",
  resetUnknown: "reset unknown",
  never: "never"
};

export const detailCopyResources = defineLocaleResources(en, {
  zh: {
    titlePrefix: "Codex",
    detailsSubtitle: "账号详情与使用情况",
    current: "当前",
    saved: "已保存",
    showSensitive: "显示隐私信息",
    hideSensitive: "隐藏隐私信息",
    currentlyActive: "当前激活",
    savedAccount: "已保存账号",
    teamName: "团队空间",
    login: "登录方式",
    loginTime: "登录时间",
    userId: "用户 ID",
    status: "状态",
    hourlyQuota: "5小时配额",
    weeklyQuota: "每周配额",
    reviewQuota: "代码审查配额",
    reset: "重置",
    usageTitle: "使用详情",
    usageHint: "使用数据为近似值，可能延迟更新。",
    usageSubtitle: "个人使用",
    usageLoading: "正在加载每日使用情况...",
    usageEmpty: "在此期间无数据",
    usageError: "每日使用情况加载失败。",
    rangeLabelTemplate: "最近 {days} 天",
    metadata: "元数据",
    accountId: "账号 ID",
    organizationId: "组织 ID",
    lastQuotaRefresh: "最近刷新",
    resetUnknown: "重置时间未知",
    never: "从未"
  },
  "zh-hant": {
    detailsSubtitle: "帳號詳情與使用情況",
    current: "目前",
    saved: "已儲存",
    currentlyActive: "目前啟用",
    savedAccount: "已儲存帳號",
    teamName: "團隊空間",
    login: "登入方式",
    loginTime: "登入時間",
    status: "狀態",
    hourlyQuota: "5小時配額",
    weeklyQuota: "每週配額",
    reviewQuota: "程式碼審查配額",
    reset: "重置",
    usageTitle: "使用詳情",
    usageHint: "使用資料為近似值，可能會延遲更新。",
    usageSubtitle: "個人使用",
    usageLoading: "正在載入每日使用情況...",
    usageEmpty: "此期間沒有資料",
    usageError: "每日使用情況載入失敗。",
    rangeLabelTemplate: "最近 {days} 天",
    metadata: "中繼資料",
    accountId: "帳號 ID",
    organizationId: "組織 ID",
    lastQuotaRefresh: "最近重新整理",
    resetUnknown: "重置時間未知",
    never: "從未"
  },
  ja: {
    detailsSubtitle: "アカウント詳細と使用状況",
    current: "現在",
    saved: "保存済み",
    currentlyActive: "現在アクティブ",
    savedAccount: "保存済みアカウント",
    teamName: "チーム",
    login: "ログイン",
    loginTime: "ログイン時刻",
    status: "状態",
    hourlyQuota: "5時間クォータ",
    weeklyQuota: "週間クォータ",
    reviewQuota: "レビュークォータ",
    reset: "リセット",
    usageTitle: "使用状況",
    usageHint: "使用データは概算で、更新が遅れる場合があります。",
    usageSubtitle: "個人使用量",
    usageLoading: "日次使用量を読み込み中...",
    usageEmpty: "この期間のデータはありません",
    usageError: "日次使用量の読み込みに失敗しました。",
    rangeLabelTemplate: "直近 {days} 日",
    metadata: "メタデータ",
    lastQuotaRefresh: "最終クォータ更新",
    resetUnknown: "リセット時刻不明",
    never: "なし"
  },
  es: {
    detailsSubtitle: "Detalles de la cuenta y uso",
    current: "Actual",
    saved: "Guardado",
    currentlyActive: "Actualmente activa",
    savedAccount: "Cuenta guardada",
    teamName: "Equipo",
    login: "Inicio de sesión",
    loginTime: "Hora de inicio",
    status: "Estado",
    hourlyQuota: "Cuota de 5 h",
    weeklyQuota: "Cuota semanal",
    reviewQuota: "Cuota de revisión",
    reset: "Reinicio",
    usageTitle: "Detalles de uso",
    usageHint: "Los datos de uso son aproximados y pueden tardar en actualizarse.",
    usageSubtitle: "Uso personal",
    usageLoading: "Cargando uso diario...",
    usageEmpty: "No hay datos en este periodo",
    usageError: "No se pudo cargar el uso diario.",
    rangeLabelTemplate: "Últimos {days} días",
    metadata: "Metadatos",
    lastQuotaRefresh: "Última actualización de cuota",
    resetUnknown: "reinicio desconocido",
    never: "nunca"
  },
  de: {
    detailsSubtitle: "Kontodetails und Nutzung",
    current: "Aktuell",
    saved: "Gespeichert",
    currentlyActive: "Derzeit aktiv",
    savedAccount: "Gespeichertes Konto",
    teamName: "Team",
    login: "Anmeldung",
    loginTime: "Anmeldezeit",
    status: "Status",
    hourlyQuota: "5h-Kontingent",
    weeklyQuota: "Wochenkontingent",
    reviewQuota: "Review-Kontingent",
    reset: "Zurücksetzen",
    usageTitle: "Nutzungsdetails",
    usageHint: "Nutzungsdaten sind ungefähr und können verzögert sein.",
    usageSubtitle: "Persönliche Nutzung",
    usageLoading: "Tägliche Nutzung wird geladen...",
    usageEmpty: "Keine Daten in diesem Zeitraum",
    usageError: "Tägliche Nutzung konnte nicht geladen werden.",
    rangeLabelTemplate: "Letzte {days} Tage",
    metadata: "Metadaten",
    lastQuotaRefresh: "Letzte Kontingentaktualisierung",
    resetUnknown: "Zurücksetzung unbekannt",
    never: "nie"
  },
  fr: {
    detailsSubtitle: "Détails du compte et utilisation",
    current: "Actuel",
    saved: "Enregistré",
    currentlyActive: "Actuellement actif",
    savedAccount: "Compte enregistré",
    teamName: "Équipe",
    login: "Connexion",
    loginTime: "Heure de connexion",
    status: "Statut",
    hourlyQuota: "Quota 5 h",
    weeklyQuota: "Quota hebdomadaire",
    reviewQuota: "Quota de revue",
    reset: "Réinitialisation",
    usageTitle: "Détails d'utilisation",
    usageHint: "Les données d'utilisation sont approximatives et peuvent être retardées.",
    usageSubtitle: "Utilisation personnelle",
    usageLoading: "Chargement de l'utilisation quotidienne...",
    usageEmpty: "Aucune donnée pour cette période",
    usageError: "Échec du chargement de l'utilisation quotidienne.",
    rangeLabelTemplate: "{days} derniers jours",
    metadata: "Métadonnées",
    lastQuotaRefresh: "Dernière actualisation du quota",
    resetUnknown: "réinitialisation inconnue",
    never: "jamais"
  },
  "pt-br": {
    detailsSubtitle: "Detalhes da conta e uso",
    current: "Atual",
    saved: "Salvo",
    currentlyActive: "Ativa no momento",
    savedAccount: "Conta salva",
    teamName: "Equipe",
    login: "Login",
    loginTime: "Hora do login",
    status: "Status",
    hourlyQuota: "Cota de 5 h",
    weeklyQuota: "Cota semanal",
    reviewQuota: "Cota de revisão",
    reset: "Reinício",
    usageTitle: "Detalhes de uso",
    usageHint: "Os dados de uso são aproximados e podem demorar a atualizar.",
    usageSubtitle: "Uso pessoal",
    usageLoading: "Carregando uso diário...",
    usageEmpty: "Sem dados neste período",
    usageError: "Falha ao carregar o uso diário.",
    rangeLabelTemplate: "Últimos {days} dias",
    metadata: "Metadados",
    lastQuotaRefresh: "Última atualização da cota",
    resetUnknown: "reinício desconhecido",
    never: "nunca"
  },
  ru: {
    detailsSubtitle: "Данные аккаунта и использование",
    current: "Текущий",
    saved: "Сохранен",
    currentlyActive: "Сейчас активен",
    savedAccount: "Сохраненный аккаунт",
    teamName: "Команда",
    login: "Вход",
    loginTime: "Время входа",
    status: "Статус",
    hourlyQuota: "Квота на 5 ч",
    weeklyQuota: "Недельная квота",
    reviewQuota: "Квота на ревью",
    reset: "Сброс",
    usageTitle: "Детали использования",
    usageHint: "Данные использования приблизительные и могут обновляться с задержкой.",
    usageSubtitle: "Личное использование",
    usageLoading: "Загрузка ежедневного использования...",
    usageEmpty: "Нет данных за этот период",
    usageError: "Не удалось загрузить ежедневное использование.",
    rangeLabelTemplate: "Последние {days} дн.",
    metadata: "Метаданные",
    lastQuotaRefresh: "Последнее обновление квоты",
    resetUnknown: "время сброса неизвестно",
    never: "никогда"
  },
  ko: {
    detailsSubtitle: "계정 상세 및 사용량",
    current: "현재",
    saved: "저장됨",
    currentlyActive: "현재 활성",
    savedAccount: "저장된 계정",
    teamName: "팀",
    login: "로그인",
    loginTime: "로그인 시간",
    status: "상태",
    hourlyQuota: "5시간 할당량",
    weeklyQuota: "주간 할당량",
    reviewQuota: "리뷰 할당량",
    reset: "재설정",
    usageTitle: "사용량 상세",
    usageHint: "사용량 데이터는 대략값이며 업데이트가 지연될 수 있습니다.",
    usageSubtitle: "개인 사용량",
    usageLoading: "일별 사용량을 불러오는 중...",
    usageEmpty: "이 기간에는 데이터가 없습니다",
    usageError: "일별 사용량을 불러오지 못했습니다.",
    rangeLabelTemplate: "최근 {days}일",
    metadata: "메타데이터",
    lastQuotaRefresh: "최근 할당량 새로고침",
    resetUnknown: "재설정 시간 알 수 없음",
    never: "없음"
  },
  it: {
    detailsSubtitle: "Dettagli account e utilizzo",
    current: "Corrente",
    saved: "Salvato",
    currentlyActive: "Attualmente attivo",
    savedAccount: "Account salvato",
    teamName: "Team",
    login: "Accesso",
    loginTime: "Ora di accesso",
    status: "Stato",
    hourlyQuota: "Quota 5 h",
    weeklyQuota: "Quota settimanale",
    reviewQuota: "Quota review",
    reset: "Reset",
    usageTitle: "Dettagli utilizzo",
    usageHint: "I dati di utilizzo sono approssimativi e potrebbero essere in ritardo.",
    usageSubtitle: "Utilizzo personale",
    usageLoading: "Caricamento utilizzo giornaliero...",
    usageEmpty: "Nessun dato per questo periodo",
    usageError: "Impossibile caricare l'utilizzo giornaliero.",
    rangeLabelTemplate: "Ultimi {days} giorni",
    metadata: "Metadati",
    lastQuotaRefresh: "Ultimo aggiornamento quota",
    resetUnknown: "reset sconosciuto",
    never: "mai"
  },
  tr: {
    detailsSubtitle: "Hesap ayrıntıları ve kullanım",
    current: "Geçerli",
    saved: "Kayıtlı",
    currentlyActive: "Şu anda etkin",
    savedAccount: "Kayıtlı hesap",
    teamName: "Ekip",
    login: "Giriş",
    loginTime: "Giriş zamanı",
    status: "Durum",
    hourlyQuota: "5 saat kotası",
    weeklyQuota: "Haftalık kota",
    reviewQuota: "İnceleme kotası",
    reset: "Sıfırlama",
    usageTitle: "Kullanım ayrıntıları",
    usageHint: "Kullanım verileri yaklaşık değerlerdir ve gecikmeli güncellenebilir.",
    usageSubtitle: "Kişisel kullanım",
    usageLoading: "Günlük kullanım yükleniyor...",
    usageEmpty: "Bu dönemde veri yok",
    usageError: "Günlük kullanım yüklenemedi.",
    rangeLabelTemplate: "Son {days} gün",
    metadata: "Meta veriler",
    lastQuotaRefresh: "Son kota yenileme",
    resetUnknown: "sıfırlama bilinmiyor",
    never: "asla"
  },
  pl: {
    detailsSubtitle: "Szczegóły konta i użycia",
    current: "Bieżące",
    saved: "Zapisane",
    currentlyActive: "Aktualnie aktywne",
    savedAccount: "Zapisane konto",
    teamName: "Zespół",
    login: "Logowanie",
    loginTime: "Czas logowania",
    status: "Status",
    hourlyQuota: "Limit 5 h",
    weeklyQuota: "Limit tygodniowy",
    reviewQuota: "Limit przeglądu",
    reset: "Reset",
    usageTitle: "Szczegóły użycia",
    usageHint: "Dane użycia są przybliżone i mogą być opóźnione.",
    usageSubtitle: "Użycie osobiste",
    usageLoading: "Ładowanie dziennego użycia...",
    usageEmpty: "Brak danych w tym okresie",
    usageError: "Nie udało się załadować dziennego użycia.",
    rangeLabelTemplate: "Ostatnie {days} dni",
    metadata: "Metadane",
    lastQuotaRefresh: "Ostatnie odświeżenie limitu",
    resetUnknown: "reset nieznany",
    never: "nigdy"
  },
  cs: {
    detailsSubtitle: "Detaily účtu a využití",
    current: "Aktuální",
    saved: "Uložený",
    currentlyActive: "Právě aktivní",
    savedAccount: "Uložený účet",
    teamName: "Tým",
    login: "Přihlášení",
    loginTime: "Čas přihlášení",
    status: "Stav",
    hourlyQuota: "Kvóta na 5 h",
    weeklyQuota: "Týdenní kvóta",
    reviewQuota: "Kvóta revize",
    reset: "Reset",
    usageTitle: "Detaily využití",
    usageHint: "Data o využití jsou přibližná a mohou mít zpoždění.",
    usageSubtitle: "Osobní využití",
    usageLoading: "Načítání denního využití...",
    usageEmpty: "V tomto období nejsou žádná data",
    usageError: "Nepodařilo se načíst denní využití.",
    rangeLabelTemplate: "Posledních {days} dní",
    metadata: "Metadata",
    lastQuotaRefresh: "Poslední obnovení kvóty",
    resetUnknown: "čas resetu neznámý",
    never: "nikdy"
  },
  ar: {
    detailsSubtitle: "تفاصيل الحساب والاستخدام",
    current: "الحالي",
    saved: "محفوظ",
    currentlyActive: "نشط حاليًا",
    savedAccount: "الحساب المحفوظ",
    teamName: "الفريق",
    login: "تسجيل الدخول",
    loginTime: "وقت تسجيل الدخول",
    status: "الحالة",
    hourlyQuota: "حصة 5 ساعات",
    weeklyQuota: "الحصة الأسبوعية",
    reviewQuota: "حصة المراجعة",
    reset: "إعادة التعيين",
    usageTitle: "تفاصيل الاستخدام",
    usageHint: "بيانات الاستخدام تقريبية وقد تتأخر في التحديث.",
    usageSubtitle: "الاستخدام الشخصي",
    usageLoading: "جار تحميل الاستخدام اليومي...",
    usageEmpty: "لا توجد بيانات لهذه الفترة",
    usageError: "فشل تحميل الاستخدام اليومي.",
    rangeLabelTemplate: "آخر {days} يومًا",
    metadata: "البيانات الوصفية",
    lastQuotaRefresh: "آخر تحديث للحصة",
    resetUnknown: "وقت إعادة التعيين غير معروف",
    never: "أبدًا"
  },
  vi: {
    detailsSubtitle: "Chi tiết tài khoản và mức sử dụng",
    current: "Hiện tại",
    saved: "Đã lưu",
    currentlyActive: "Đang hoạt động",
    savedAccount: "Tài khoản đã lưu",
    teamName: "Nhóm",
    login: "Đăng nhập",
    loginTime: "Thời gian đăng nhập",
    status: "Trạng thái",
    hourlyQuota: "Hạn mức 5 giờ",
    weeklyQuota: "Hạn mức tuần",
    reviewQuota: "Hạn mức review",
    reset: "Đặt lại",
    usageTitle: "Chi tiết sử dụng",
    usageHint: "Dữ liệu sử dụng chỉ mang tính gần đúng và có thể cập nhật chậm.",
    usageSubtitle: "Sử dụng cá nhân",
    usageLoading: "Đang tải mức sử dụng hằng ngày...",
    usageEmpty: "Không có dữ liệu trong giai đoạn này",
    usageError: "Không tải được mức sử dụng hằng ngày.",
    rangeLabelTemplate: "{days} ngày gần nhất",
    metadata: "Siêu dữ liệu",
    lastQuotaRefresh: "Lần làm mới hạn mức gần nhất",
    resetUnknown: "không rõ thời điểm đặt lại",
    never: "chưa bao giờ"
  }
});
